#pragma once
#include "ColourMapSafety.h"
#include "ColourVision.h"
#include <QString>
#include <QVector>
#include <cmath>
#include <limits>

// =========================================================================
// What to TELL the person about a colour map, and what to draw instead.
//
// Everything here answers questions that ColourMapSafety.h has already
// measured. It exists as its own header for two reasons: ColourMapSafety.h is
// generated by tools/measure_colourmap_cvd.py and must not be hand-edited, and
// ColourVision.h cannot reach the safety table at all because the table
// includes it.
//
// THE ONE RULE HERE: there is a single answer to "can this reader use this
// map", and it is colourmaps::mapIsSafeFor.
//
// That rule is written down because it was broken. A second, independent
// measurement lived in ColourVision.h - sample the ramp, simulate it, find the
// closest pair a fifth of the scale apart, compare against a floor - and drove
// the greying-out of entries in the map chooser, while mapIsSafeFor drove the
// substitution that actually changes the figure. Two measurements of one
// property disagreed on 48 of 252 map-and-reader pairs: Jet was quietly
// swapped for a deuteranope while the chooser offered it as fine, and Accent
// was greyed out as unusable while the figure went on being painted in it.
// Neither half was lying; there were simply two ideas of what "safe" meant,
// which is the same fault the dichromat matrices had before they were moved
// into one place.
//
// The generated table wins because it is the better measurement, not because
// it came first: it scores each map against the reading task its ROLE exists
// for - ordering for a sequential ramp, side-and-distance for a diverging one,
// angle for a cyclic one, telling apart for a categorical one - and it
// includes a lightness-monotonicity requirement that a worst-pair distance
// cannot express. It also knows that Monochrome is a REQUEST for no colour
// rather than a question about legibility, which a distance measure gets
// confidently wrong.
// =========================================================================

namespace graphvis {
namespace colourmaps {

// Whether a map carries any values at all, as the extent of its ramp in
// CIELAB. White is a flat fill and is the reason this exists: it is the one
// entry marked safe in Monochrome - correctly, since a request for no colour is
// exactly what it satisfies - so it was the only candidate of its role and
// Prism, Flag and Colorcube were all "substituted" into a blank figure. A map
// that cannot be unreadable because it shows nothing is not a substitute.
inline bool carriesValues(const QString& name){
    constexpr int kSamples=33;
    const auto* table=tableFor(name);
    detail::LabColour lo{100,0,0},hi{0,0,0};
    bool first=true;
    for(int i=0;i<kSamples;++i){
        const QColor c=sample(table,double(i)/(kSamples-1));
        const detail::LabColour lab=detail::labOf(c.redF(),c.greenF(),c.blueF());
        if(first){ lo=hi=lab; first=false; continue; }
        lo.l=qMin(lo.l,lab.l); lo.a=qMin(lo.a,lab.a); lo.b=qMin(lo.b,lab.b);
        hi.l=qMax(hi.l,lab.l); hi.a=qMax(hi.a,lab.a); hi.b=qMax(hi.b,lab.b);
    }
    return detail::labDistance(lo,hi)>=5.0;
}

// The map this reader should actually be shown, given what they chose.
//
// safeSubstituteFor already answers this, but it answers it with ONE map per
// role: every unreadable sequential map becomes Cividis, whoever chose
// whatever. That is safe and it is blunt - a person who picked Hot, a person
// who picked Terrain and a person who picked Gist Ncar all get the same
// blue-yellow ramp, and none of them gets anything resembling what they asked
// for. The role is the part that must not change, because it is what the
// figure CLAIMS about the data; the particular map inside that role is taste,
// and taste should be preserved where it can be.
//
// So: among the maps that share the chosen map's role AND pass for this
// reader, take the one closest to the chosen map in CIELAB.
//
// Closest AS SOMEONE WITH STANDARD VISION SEES IT, which is the deliberate
// half of this. A figure is read by people with all kinds of colour vision,
// and the point of substituting is to make it legible for this reader while
// keeping it as near as possible to the author's intent for everyone else.
// Matching on the reader's own perception would instead choose whichever map
// happens to collapse the same way, which is the opposite of the goal.
//
// Falls back to safeSubstituteFor when the role offers nothing that passes, so
// this can only ever be as good as the fixed table and never worse.
// The nearest map to `name` out of `candidates`, in CIELAB, as someone with
// STANDARD vision sees it.
//
// One implementation, because there are now two questions with the same shape -
// "the nearest SAFE map" and "the nearest RECOMMENDED map" - and two copies of
// a thirty-line distance calculation is how they come to disagree about what
// "nearest" means.
//
// Standard vision is the deliberate half. A figure is read by people with all
// kinds of colour vision, and the point of substituting is to make it legible
// for THIS reader while keeping it as close as possible to the author's intent
// for the rest of them. Matching through the reader's own deficiency would
// instead pick whichever map happens to collapse the same way.
inline QString nearestAmong(const QString& name,const QStringList& candidates){
    if(candidates.isEmpty()) return QString();
    constexpr int kSamples=33;
    const auto profile=[](const QString& map){
        QVector<detail::LabColour> out;
        const auto* table=tableFor(map);
        out.reserve(kSamples);
        for(int i=0;i<kSamples;++i){
            const QColor c=sample(table,double(i)/(kSamples-1));
            out.append(detail::labOf(c.redF(),c.greenF(),c.blueF()));
        }
        return out;
    };
    const QVector<detail::LabColour> want=profile(name);
    QString best;
    double bestDistance=std::numeric_limits<double>::max();
    for(const QString& candidate:candidates){
        if(candidate==name) continue;
        if(!carriesValues(candidate)) continue;
        const QVector<detail::LabColour> have=profile(candidate);
        double sum=0.0;
        for(int i=0;i<kSamples;++i) sum+=detail::labDistance(want[i],have[i]);
        const double mean=sum/kSamples;
        // Ties broken by name so the answer is stable across runs and
        // platforms. A substitution that changed between sessions would look
        // like the setting drifting on its own.
        if(mean<bestDistance||(mean==bestDistance&&candidate<best)){
            bestDistance=mean;
            best=candidate;
        }
    }
    return best;
}

inline QString nearestSafeFor(const QString& name,ColourVision mode){
    if(mapIsSafeFor(name,mode)) return name;
    const MapRole role=roleOf(name);
    QStringList sameRole;
    for(const SafetyEntry& entry:safety()){
        const QString candidate=QString::fromLatin1(entry.name);
        if(entry.role!=role) continue;
        if(!mapIsSafeFor(candidate,mode)) continue;
        sameRole.append(candidate);
    }
    const QString found=nearestAmong(name,sameRole);
    return found.isEmpty()?safeSubstituteFor(name,mode):found;
}

// The maps to OFFER this reader, for the chooser's "Best for" group.
//
// Straight from the generated table now. This was a ranking computed here, by
// sorting the passing maps by worstCollapse - and it reproduced, exactly, the
// mistake the generator's own docstring warns about: "ranked by separation
// alone the substitute came out as Afmhot, a black-red-yellow heat ramp that
// scores well because it is violently contrasty, ahead of Cividis, which
// exists for precisely this purpose." It duly put Afmhot first for protanopia.
//
// That was a THIRD implementation of "which map is best", contradicting the
// reasoning already written down beside the measurement. The generator now
// emits the whole ranking instead of only its first element, so there is one
// ordering, arrived at once, with the preferred tier consulted before the
// score.
inline QStringList bestForReader(ColourVision mode){
    if(mode==ColourVision::Standard) return {};
    QStringList out;
    for(MapRole role:{MapRole::Sequential,MapRole::Diverging,
                      MapRole::Categorical,MapRole::Cyclic})
        out+=recommendedMaps(role,mode);
    return out;
}

// What to DRAW in when a colour-vision mode has been asked for.
//
// Stronger than nearestSafeFor, and this is the difference that was reported.
//
// mapIsSafeFor is a threshold with a floor of 10 dE. Seismic scores 10.7 for a
// protanope, so it passes, so nothing was substituted, so turning on
// colour-blind mode left the figure looking exactly as it had - and was
// reported as the setting doing nothing. It was not doing nothing; it was
// applying the wrong standard.
//
// "Passes" is the right bar for greying out a control, because refusing
// somebody a map they can in fact read would be wrong. It is NOT the right bar
// for what to draw when a person has explicitly asked for a colour-blind mode.
// That request does not mean "give me anything above the minimum", it means
// "make this easy for me to read". So the drawn map is held to the recommended
// set instead, and Seismic moves to Coolwarm - the same blue-white-red shape,
// 15.9 instead of 10.7.
//
// The ROLE still cannot change, for the same reason as everywhere else: it is
// what the figure claims about the data.
//
// And the person's choice is still kept. This decides what is PAINTED;
// PlotCanvas keeps chosenColourMap_ untouched, the chooser goes on showing it,
// the note beside the chooser says what is being drawn instead, and turning the
// mode off brings the original straight back.
inline QString recommendedFor(const QString& name,ColourVision mode){
    if(mode==ColourVision::Standard) return name;
    const MapRole role=roleOf(name);
    const QStringList good=recommendedMaps(role,mode);
    // Already one of the good ones: leave it entirely alone. Someone who has
    // chosen well should not have their choice moved sideways - which is what
    // an earlier version did to Viridis, of all maps.
    if(good.contains(name)) return name;

    const QString found=nearestAmong(name,good);
    // Nothing recommended in this role - fall back to the safety rule, which
    // can only ever be as good as this and never worse.
    return found.isEmpty()?nearestSafeFor(name,mode):found;
}

// Empty when this reader can use this map; otherwise one sentence saying what
// goes wrong and what they will get instead, for a tooltip beside a control
// that has been disabled.
//
// Names the ACTUAL substitute rather than recommending a fixed pair of maps.
// The previous wording ended "Viridis and Cividis keep their separation",
// which was advice the program did not take: it was about to draw the figure
// in something else entirely, and for a diverging or categorical map Viridis
// would have been the wrong answer anyway.
inline QString colourMapWarning(const QString& map,ColourVision mode){
    if(mode==ColourVision::Standard) return QString();
    if(mapIsSafeFor(map,mode)) return QString();

    const QString instead=nearestSafeFor(map,mode);
    if(mode==ColourVision::Monochrome)
        return QStringLiteral("%1 carries its values in colour, which this "
                              "setting removes. The figure is drawn in %2.")
            .arg(map,instead);

    QString what;
    switch(roleOf(map)){
    case MapRole::Diverging:
        what=QStringLiteral("its two sides come out the same colour for this "
                            "reader, so the centre it is drawn around is lost");
        break;
    case MapRole::Categorical:
        what=QStringLiteral("several of its categories come out the same "
                            "colour for this reader");
        break;
    case MapRole::Cyclic:
        what=QStringLiteral("it stops running evenly round the circle for this "
                            "reader, so an angle cannot be read off it");
        break;
    default:
        what=QStringLiteral("values far apart on the scale come out nearly the "
                            "same colour for this reader, so the order cannot "
                            "be read off it");
        break;
    }
    return QStringLiteral("%1: %2. The figure is drawn in %3 instead, which "
                          "keeps the same kind of scale.").arg(map,what,instead);
}

} // namespace colourmaps
} // namespace graphvis
