#pragma once
#include <QString>
#include "ColourMaps.h"
#include "ColourVision.h"

// =========================================================================
// ColourMapSafety.h - GENERATED by tools/measure_colourmap_cvd.py.
// Do not edit by hand; re-run the script.
//
// Choosing a colour-vision mode used to change the SERIES palette and
// nothing else. On a surface, a heat map, a contour or a vector field there
// are no series - the colour map IS the data - so on exactly the plots where
// the setting matters most it appeared to do nothing at all. This table is
// what lets the setting reach them.
//
// Every map was simulated through Machado, Oliveira & Fernandes (2009) at
// severity 1.0 and measured against the reading task its category exists
// for - ordering for a sequential ramp, side-and-distance for a diverging
// one, angle for a cyclic one, telling apart for a categorical one. Pass is
// a worst separation of 10 dE76 with at least
// 0.80 of steps running the same way in lightness, the same
// margin ColourVision.h uses for the series palettes.
// =========================================================================

namespace graphvis {
namespace colourmaps {

enum class MapRole { Sequential, Diverging, Cyclic, Categorical, Utility };

struct SafetyEntry {
    const char* name;
    MapRole role;
    // Bit 0 protanopia, 1 deuteranopia, 2 tritanopia, 3 monochrome,
    // 4 normal vision. Set means the map is right for that viewer.
    //
    // Bits 0-2 and 4 are the measurement: does the map survive being
    // simulated through that deficiency. Bit 3 is NOT - monochrome is a
    // request for no colour rather than a question about legibility, and
    // answering it with the measurement is a bug that shipped: Plasma
    // scores 16.9 in greyscale, so "safe in monochrome" said yes and a
    // person who had asked for no colour kept a full-colour surface. Bit 3
    // is set only for the maps that are grey by construction.
    unsigned char passes;
};

inline const QVector<SafetyEntry>& safety(){
    static const QVector<SafetyEntry> entries{
        {"Parula",MapRole::Sequential,0x17},  // normal 44.1  protan 30.8  deutan 26.9  tritan 12.8  mono 8.1
        {"Viridis",MapRole::Sequential,0x17},  // normal 38.5  protan 24.3  deutan 18.6  tritan 18.5  mono 18.4
        {"Plasma",MapRole::Sequential,0x17},  // normal 27.0  protan 11.8  deutan 26.3  tritan 21.0  mono 16.9
        {"Inferno",MapRole::Sequential,0x17},  // normal 37.3  protan 19.0  deutan 25.8  tritan 22.9  mono 22.3
        {"Magma",MapRole::Sequential,0x17},  // normal 34.1  protan 18.8  deutan 25.4  tritan 22.5  mono 22.2
        {"Cividis",MapRole::Sequential,0x17},  // normal 23.9  protan 22.0  deutan 24.6  tritan 18.3  mono 18.4
        {"Turbo",MapRole::Sequential,0x00},  // normal 52.3  protan 18.0  deutan 14.2  tritan 26.7  mono 0.0
        {"Hot",MapRole::Sequential,0x17},  // normal 30.9  protan 27.7  deutan 23.9  tritan 13.5  mono 3.1
        {"Afmhot",MapRole::Sequential,0x17},  // normal 48.2  protan 32.1  deutan 30.4  tritan 11.0  mono 3.0
        {"Gist Heat",MapRole::Sequential,0x17},  // normal 35.0  protan 21.4  deutan 25.6  tritan 28.1  mono 18.4
        {"Copper",MapRole::Sequential,0x17},  // normal 19.4  protan 16.9  deutan 13.7  tritan 17.2  mono 14.5
        {"Bone",MapRole::Sequential,0x17},  // normal 24.4  protan 21.4  deutan 23.6  tritan 24.9  mono 22.4
        {"Pink",MapRole::Sequential,0x17},  // normal 17.3  protan 16.5  deutan 15.5  tritan 11.5  mono 9.1
        {"Gray",MapRole::Sequential,0x1f},  // normal 23.0  protan 23.0  deutan 23.0  tritan 23.0  mono 23.0
        {"Greys",MapRole::Sequential,0x1f},  // normal 13.7  protan 13.7  deutan 13.7  tritan 13.7  mono 13.7
        {"Purples",MapRole::Sequential,0x17},  // normal 14.0  protan 13.7  deutan 13.9  tritan 11.8  mono 11.6
        {"Blues",MapRole::Sequential,0x17},  // normal 16.1  protan 14.5  deutan 16.7  tritan 16.1  mono 12.4
        {"Greens",MapRole::Sequential,0x17},  // normal 22.5  protan 18.3  deutan 16.1  tritan 14.6  mono 9.8
        {"Oranges",MapRole::Sequential,0x17},  // normal 22.7  protan 21.1  deutan 17.6  tritan 19.0  mono 11.0
        {"Reds",MapRole::Sequential,0x17},  // normal 19.8  protan 20.2  deutan 18.7  tritan 21.4  mono 16.5
        {"YlOrBr",MapRole::Sequential,0x17},  // normal 28.9  protan 24.6  deutan 19.9  tritan 17.8  mono 8.9
        {"YlOrRd",MapRole::Sequential,0x17},  // normal 26.6  protan 22.1  deutan 17.3  tritan 20.9  mono 11.4
        {"OrRd",MapRole::Sequential,0x17},  // normal 22.8  protan 22.1  deutan 20.6  tritan 21.0  mono 10.6
        {"PuRd",MapRole::Sequential,0x17},  // normal 25.6  protan 22.5  deutan 16.0  tritan 20.7  mono 15.3
        {"RdPu",MapRole::Sequential,0x17},  // normal 23.2  protan 16.2  deutan 14.6  tritan 23.2  mono 13.8
        {"BuPu",MapRole::Sequential,0x17},  // normal 18.9  protan 18.0  deutan 19.0  tritan 17.9  mono 15.3
        {"GnBu",MapRole::Sequential,0x17},  // normal 17.7  protan 10.2  deutan 11.6  tritan 13.2  mono 8.7
        {"PuBu",MapRole::Sequential,0x17},  // normal 17.3  protan 16.6  deutan 17.8  tritan 15.3  mono 14.0
        {"YlGnBu",MapRole::Sequential,0x17},  // normal 18.7  protan 10.6  deutan 11.6  tritan 17.0  mono 10.8
        {"PuBuGn",MapRole::Sequential,0x17},  // normal 17.1  protan 16.1  deutan 17.7  tritan 15.3  mono 14.0
        {"BuGn",MapRole::Sequential,0x14},  // normal 13.2  protan 7.4  deutan 8.6  tritan 14.7  mono 8.0
        {"YlGn",MapRole::Sequential,0x17},  // normal 22.7  protan 14.0  deutan 14.3  tritan 10.6  mono 8.3
        {"Coolwarm",MapRole::Diverging,0x17},  // normal 22.9  protan 15.9  deutan 16.1  tritan 15.7  mono 0.0
        {"Bwr",MapRole::Diverging,0x13},  // normal 24.7  protan 13.9  deutan 13.2  tritan 7.5  mono 4.1
        {"Seismic",MapRole::Diverging,0x17},  // normal 13.9  protan 10.7  deutan 11.2  tritan 10.8  mono 11.1
        {"Spectral",MapRole::Diverging,0x14},  // normal 14.6  protan 8.1  deutan 9.5  tritan 11.7  mono 4.5
        {"RdBu",MapRole::Diverging,0x17},  // normal 16.6  protan 13.6  deutan 16.5  tritan 18.9  mono 0.1
        {"RdGy",MapRole::Diverging,0x16},  // normal 14.4  protan 5.3  deutan 14.4  tritan 14.4  mono 0.0
        {"RdYlBu",MapRole::Diverging,0x17},  // normal 19.4  protan 17.1  deutan 16.5  tritan 18.9  mono 0.3
        {"RdYlGn",MapRole::Diverging,0x14},  // normal 19.6  protan 8.5  deutan 3.3  tritan 14.2  mono 2.5
        {"PuOr",MapRole::Diverging,0x17},  // normal 18.9  protan 18.4  deutan 18.3  tritan 14.5  mono 5.5
        {"BrBG",MapRole::Diverging,0x16},  // normal 19.2  protan 8.9  deutan 11.5  tritan 16.1  mono 1.8
        {"PRGn",MapRole::Diverging,0x17},  // normal 21.8  protan 18.5  deutan 15.7  tritan 14.1  mono 7.6
        {"PiYG",MapRole::Diverging,0x11},  // normal 19.7  protan 13.3  deutan 9.4  tritan 9.2  mono 3.6
        {"Twilight",MapRole::Cyclic,0x17},  // normal 36.7  protan 29.6  deutan 35.4  tritan 39.1  mono 0.0
        {"Twilight Shifted",MapRole::Cyclic,0x17},  // normal 36.3  protan 28.9  deutan 35.0  tritan 39.0  mono 0.0
        {"HSV",MapRole::Cyclic,0x14},  // normal 68.8  protan 4.1  deutan 1.9  tritan 13.6  mono 0.2
        {"Phase",MapRole::Cyclic,0x17},  // normal 36.3  protan 28.9  deutan 35.0  tritan 39.0  mono 0.0
        {"Cubehelix",MapRole::Sequential,0x17},  // normal 39.2  protan 16.3  deutan 23.2  tritan 24.8  mono 19.3
        {"Cool",MapRole::Sequential,0x00},  // normal 24.9  protan 0.2  deutan 0.5  tritan 17.8  mono 0.0
        {"Spring",MapRole::Sequential,0x17},  // normal 41.3  protan 29.3  deutan 25.5  tritan 12.8  mono 0.2
        {"Summer",MapRole::Sequential,0x17},  // normal 20.5  protan 19.4  deutan 20.1  tritan 10.9  mono 11.7
        {"Autumn",MapRole::Sequential,0x14},  // normal 11.8  protan 8.0  deutan 4.0  tritan 19.1  mono 3.9
        {"Winter",MapRole::Sequential,0x13},  // normal 41.6  protan 20.5  deutan 26.1  tritan 9.3  mono 3.8
        {"Binary",MapRole::Sequential,0x1f},  // normal 23.0  protan 23.0  deutan 23.0  tritan 23.0  mono 23.0
        {"Gist Gray",MapRole::Sequential,0x1f},  // normal 23.0  protan 23.0  deutan 23.0  tritan 23.0  mono 23.0
        {"Gist Yarg",MapRole::Sequential,0x1f},  // normal 23.0  protan 23.0  deutan 23.0  tritan 23.0  mono 23.0
        {"Terrain",MapRole::Sequential,0x00},  // normal 26.8  protan 1.9  deutan 1.0  tritan 6.2  mono 0.1
        {"Ocean",MapRole::Sequential,0x00},  // normal 23.0  protan 23.1  deutan 22.4  tritan 11.1  mono 0.3
        {"Gist Earth",MapRole::Sequential,0x14},  // normal 33.2  protan 7.8  deutan 8.2  tritan 17.1  mono 6.2
        {"Gist Ncar",MapRole::Sequential,0x00},  // normal 29.4  protan 1.0  deutan 3.8  tritan 12.8  mono 0.0
        {"Gnuplot",MapRole::Sequential,0x16},  // normal 19.9  protan 10.8  deutan 19.5  tritan 14.5  mono 0.0
        {"Gnuplot2",MapRole::Sequential,0x17},  // normal 27.8  protan 13.8  deutan 22.9  tritan 23.6  mono 18.7
        {"Nipy Spectral",MapRole::Sequential,0x00},  // normal 40.3  protan 0.5  deutan 4.8  tritan 14.4  mono 0.2
        {"Rainbow",MapRole::Sequential,0x00},  // normal 46.9  protan 26.9  deutan 24.4  tritan 17.6  mono 0.0
        {"Gist Rainbow",MapRole::Sequential,0x00},  // normal 61.7  protan 3.0  deutan 0.7  tritan 13.5  mono 0.0
        {"Jet",MapRole::Sequential,0x00},  // normal 53.2  protan 28.3  deutan 23.9  tritan 28.9  mono 0.0
        {"Lines",MapRole::Categorical,0x17},  // normal 34.9  protan 12.4  deutan 10.5  tritan 18.4  mono 3.2
        {"Tab10",MapRole::Categorical,0x14},  // normal 27.7  protan 4.6  deutan 7.2  tritan 15.2  mono 1.1
        {"Tab20",MapRole::Categorical,0x10},  // normal 16.6  protan 1.2  deutan 2.9  tritan 8.4  mono 0.3
        {"Tab20b",MapRole::Categorical,0x10},  // normal 12.7  protan 2.7  deutan 3.2  tritan 7.4  mono 0.1
        {"Tab20c",MapRole::Categorical,0x00},  // normal 7.3  protan 2.6  deutan 2.1  tritan 2.7  mono 0.1
        {"Set1",MapRole::Categorical,0x14},  // normal 32.7  protan 3.7  deutan 9.9  tritan 17.6  mono 0.7
        {"Set2",MapRole::Categorical,0x10},  // normal 25.4  protan 2.5  deutan 4.0  tritan 6.3  mono 0.2
        {"Set3",MapRole::Categorical,0x10},  // normal 18.1  protan 5.5  deutan 4.0  tritan 8.6  mono 0.3
        {"Paired",MapRole::Categorical,0x14},  // normal 23.6  protan 4.6  deutan 4.2  tritan 11.7  mono 0.2
        {"Accent",MapRole::Categorical,0x16},  // normal 35.2  protan 2.7  deutan 15.9  tritan 25.2  mono 1.2
        {"Dark2",MapRole::Categorical,0x14},  // normal 31.6  protan 2.1  deutan 5.8  tritan 13.4  mono 0.8
        {"Pastel1",MapRole::Categorical,0x00},  // normal 9.5  protan 1.8  deutan 2.7  tritan 5.1  mono 0.4
        {"Pastel2",MapRole::Categorical,0x10},  // normal 10.9  protan 1.4  deutan 4.9  tritan 4.8  mono 0.2
        {"Prism",MapRole::Utility,0x00},  // normal 0.0  protan 0.0  deutan 0.0  tritan 0.0  mono 0.0
        {"Flag",MapRole::Utility,0x00},  // normal 0.0  protan 0.0  deutan 0.0  tritan 0.0  mono 0.0
        {"Colorcube",MapRole::Utility,0x00},  // normal 0.0  protan 0.0  deutan 0.0  tritan 0.0  mono 0.0
        {"White",MapRole::Utility,0x08},  // normal 0.0  protan 0.0  deutan 0.0  tritan 0.0  mono 0.0
    };
    return entries;
}

inline const SafetyEntry* safetyFor(const QString& name){
    // Empty is Viridis - the same rule tableFor() follows, and it has to
    // be the same rule or the default map would be judged as an unknown
    // one and pass everything by omission. That is how the default figure
    // stayed in colour after a request for monochrome.
    const QString wanted=name.isEmpty()?QStringLiteral("Viridis"):name;
    for(const SafetyEntry& e:safety())
        if(wanted.compare(QLatin1String(e.name),Qt::CaseInsensitive)==0) return &e;
    return nullptr;
}

inline MapRole roleOf(const QString& name){
    const SafetyEntry* e=safetyFor(name);
    return e?e->role:MapRole::Sequential;
}

// Bit index for a vision mode, or -1 for Standard - which asks no question,
// so no map can fail it.
inline int visionBit(ColourVision mode){
    switch(mode){
    case ColourVision::Protanopia:  return 0;
    case ColourVision::Deuteranopia:return 1;
    case ColourVision::Tritanopia:  return 2;
    case ColourVision::Monochrome:  return 3;
    default: return -1;
    }
}

inline bool mapIsSafeFor(const QString& name,ColourVision mode){
    const int bit=visionBit(mode);
    if(bit<0) return true;
    const SafetyEntry* e=safetyFor(name);
    return e?((e->passes>>bit)&1)!=0:true;
}

// The map a reader with this vision should get instead, keeping the role so
// the substitution cannot change what the figure claims about the data.
inline QString safeSubstituteFor(const QString& name,ColourVision mode){
    switch(mode){
    case ColourVision::Protanopia:
        switch(roleOf(name)){
        case MapRole::Sequential: return QStringLiteral("Cividis");
        case MapRole::Diverging: return QStringLiteral("PuOr");
        case MapRole::Cyclic: return QStringLiteral("Twilight");
        case MapRole::Categorical: return QStringLiteral("Lines");
        default: break;
        }
        break;
    case ColourVision::Deuteranopia:
        switch(roleOf(name)){
        case MapRole::Sequential: return QStringLiteral("Cividis");
        case MapRole::Diverging: return QStringLiteral("PuOr");
        case MapRole::Cyclic: return QStringLiteral("Twilight");
        case MapRole::Categorical: return QStringLiteral("Accent");
        default: break;
        }
        break;
    case ColourVision::Tritanopia:
        switch(roleOf(name)){
        case MapRole::Sequential: return QStringLiteral("Cividis");
        case MapRole::Diverging: return QStringLiteral("PuOr");
        case MapRole::Cyclic: return QStringLiteral("Twilight");
        case MapRole::Categorical: return QStringLiteral("Accent");
        default: break;
        }
        break;
    case ColourVision::Monochrome:
        switch(roleOf(name)){
        case MapRole::Sequential: return QStringLiteral("Gray");
        case MapRole::Diverging: return QStringLiteral("Gray");
        case MapRole::Cyclic: return QStringLiteral("Gray");
        case MapRole::Categorical: return QStringLiteral("Gray");
        default: break;
        }
        break;
    default: break;
    }
    return name;
}

// What the substitution costs, or an empty string when it costs nothing.
// A substitution that loses something has to SAY so - on the figure as
// well as in the setting - or the reader is looking at a picture that
// quietly stopped showing part of what it used to.
inline QString substitutionNote(const QString& name,ColourVision mode){
    if(mapIsSafeFor(name,mode)) return QString();
    if(mode==ColourVision::Monochrome){
        switch(roleOf(name)){
        case MapRole::Diverging:
            return QStringLiteral("Monochrome: no grey ramp can mark a "
                                  "centre, so the two sides now read as "
                                  "one scale.");
        case MapRole::Categorical:
            return QStringLiteral("Monochrome: categories are separated by "
                                  "lightness alone, which carries about six "
                                  "before they merge.");
        case MapRole::Cyclic:
            return QStringLiteral("Monochrome: a grey ramp cannot close a "
                                  "cycle, so the wrap point is no longer "
                                  "visible.");
        default: return QString();
        }
    }
    return QString();
}

} // namespace colourmaps
} // namespace graphvis
