// The notebook's figures, asserted to exist.
//
// THE BUG THIS IS ABOUT. The Repeater's delegate re-declared
// `required property int index`, which FigureCell already has, and then wrote
// `index: cell.index`. The re-declaration shadowed the base's copy, so the
// base's required property was never initialised; the shadow's own value came
// from a binding on itself. Both ended at the default. Every cell in the
// notebook answered 0 when asked which figure it was - so `current` was true
// for all of them at once or none, clicking any figure selected the first, and
// the close button on any figure removed the first.
//
// The figures themselves were drawn, and drawn correctly, which is why this
// survived: it looked like it worked and acted on the wrong figure. Qt logs
// "Cannot create delegate" and "Required property index was not initialized"
// once per row and then carries on with the default.
//
// Nothing here could see it. The linter reported the shadowing as "Property
// 'index' already exists in base type 'FigureCell'" and it was read as a style
// note; the engine sweep and the property checks never load QML; and these
// tests could not instantiate this component at all, because FigureCell
// contains a PlotCanvas and the staged module had no such type. Four files were
// untestable for that reason, two of them the application's main workspaces.
// The stand-in generated by tools/run_ui_tests.py is what closed that, and this
// is the first thing to go through the hole.
//
// WHAT IT ASSERTS. That a delegate is created for every row of the model, and
// that each one is a real FigureCell with the model's index in it. Nothing
// about what is DRAWN: the canvas here is a generated stand-in that paints
// nothing, and what gets drawn is answered by the 440-engine sweep.
import QtQuick
import QtTest
import GraphVis

TestCase {
    id: suite
    name: "notebook"
    when: windowShown
    width: 600
    height: 400

    // The controller stand-in, generated from AppController.h by
    // tools/run_ui_tests.py. Not a QtObject with the four properties this test
    // happens to need: FigureCell reads seventeen off `app` before it draws
    // anything, and an incomplete stand-in produces "Unable to assign
    // [undefined] to int" once per missing one - which buries the warnings that
    // matter and makes failOnWarning unusable.
    AppController { id: fakeApp }

    Component {
        id: notebookFactory
        NotebookCanvas { }
    }

    // A cell exists for every row, and each one knows WHICH row it is.
    //
    // Both are asserted, in that order, because they failed differently: the
    // cells were all created, so a test that only counted them passed against
    // the defect. What was wrong was the number inside each one, and that is
    // the last assertion here.
    function test_every_row_of_the_model_gets_a_figure() {
        failOnWarning(/Cannot create delegate/)
        failOnWarning(/Required property/)
        failOnWarning(/Unable to assign/)

        var book = notebookFactory.createObject(suite, { app: fakeApp })
        verify(book !== null, "NotebookCanvas did not instantiate")
        compare(book.figureCount, 1, "a new notebook starts with one figure")

        var cells = findCells(book)
        compare(cells.length, 1,
                "the notebook's model has a row and no figure was created for it")

        book.addFigure("Line Chart", "")
        compare(book.figureCount, 2)
        cells = findCells(book)
        compare(cells.length, 2,
                "a figure was added to the model and no cell was created for it")

        // The index each cell was given is the row it stands for. This is what
        // the shadowed property was stealing: the base's copy stayed at its
        // default and every cell thought it was figure zero.
        var indices = []
        for (var i = 0; i < cells.length; ++i) indices.push(cells[i].index)
        indices.sort()
        compare(indices, [0, 1],
                "the cells do not carry the model's row numbers, so remove and select act on the wrong figure")

        book.destroy()
    }

    // Removing the last figure is refused, because an empty notebook has
    // nothing to select and the sidebar would be editing nothing with no way
    // back. Asserted here rather than left to the comment that says so.
    function test_the_last_figure_cannot_be_removed() {
        failOnWarning(/Unable to assign/)
        var book = notebookFactory.createObject(suite, { app: fakeApp })
        compare(book.figureCount, 1)
        book.removeFigure(0)
        compare(book.figureCount, 1,
                "the notebook was emptied, so there is nothing for the sidebar to edit")
        book.destroy()
    }

    // Depth-first for FigureCells. They are nested a few layers down - a
    // ColumnLayout, a ScrollView, a GridLayout - and the depth is layout
    // detail this test has no business pinning.
    function findCells(item) {
        var out = []
        if (item === null || item === undefined) return out
        var kids = item.children
        if (kids === undefined) return out
        for (var i = 0; i < kids.length; ++i) {
            var kid = kids[i]
            if (kid.figureEngine !== undefined && kid.index !== undefined)
                out.push(kid)
            else
                out = out.concat(findCells(kid))
        }
        return out
    }
}
