// Qt 6 delegate scoping. Without this, an id from the enclosing file is not
// legally visible inside a delegate or an inline Component - it resolves only
// because the old unbound context lookup walks out of the component, which is
// slower at every evaluation and silently breaks the moment a model role
// shares a name. Bound resolves ids at compile time; delegates declare what
// they take from the model with `required property`.
pragma ComponentBehavior: Bound
import QtQuick
import QtQuick.Controls
import QtQuick.Layouts
import GraphVis

// The manual: contents on the left, the article on the right.
//
// A BROWSER rather than more popups. The Help menu had one hand-written popup
// on it - "Which renderer should I use?" - and every further question would
// have been another popup, each one a separate piece of QML that nobody could
// search and that only appeared if you already knew the menu item existed.
//
// The content is data, not markup: config/help_topics.json, embedded in the
// executable, generated by tools/make_help.py from the hand-written half plus
// the program's own tables. Adding a topic is an edit to help_written.json.
//
// SECTIONED, because the first version was a flat list of fourteen topics and
// a flat list stops working somewhere around thirty. There are eighty-six. A
// reader who does not know the name of the thing they want has to be able to
// find it by where it lives, which is what the section headers in the contents
// are for; the search is for the reader who does know the name.
Popup {
    id: root
    parent: Overlay.overlay
    anchors.centerIn: Overlay.overlay
    width: Math.min(1040, Overlay.overlay ? Overlay.overlay.width - 60 : 900)
    height: Math.min(720, Overlay.overlay ? Overlay.overlay.height - 60 : 620)
    modal: true
    focus: true
    padding: 0

    // The topic to show when it opens, by id. Empty means the first one.
    property string startAt: ""
    // ...or a whole section, opened at its first topic. The Help menu offers
    // both, because "show me everything about colour" and "answer this exact
    // question" are different arrivals.
    property string startSection: ""
    property var app: null

    readonly property var topics: root.app ? root.app.helpTopics : []
    readonly property var sections: root.app ? root.app.helpSections : []
    property string query: ""
    property int current: 0

    // Where the reader has been, so Back works. A manual whose cross-references
    // are one-way sends people out and leaves them to find their way home
    // through the contents, which is how a see-also link stops being used.
    property var history: []

    // Title, keywords and body all searched. Somebody looking for "colourblind"
    // should find the colour-vision topic whether or not that word is in its
    // title, which is what the keywords are for.
    //
    // Topics arrive already in section order from the generator, so filtering
    // preserves that order and the headers below need no sorting.
    readonly property var shown: {
        var q = root.query.trim().toLowerCase()
        var out = []
        for (var i = 0; i < root.topics.length; ++i) {
            var t = root.topics[i]
            if (q === ""
                || (t.title || "").toLowerCase().indexOf(q) >= 0
                || (t.keywords || "").toLowerCase().indexOf(q) >= 0
                || (t.body || "").toLowerCase().indexOf(q) >= 0)
                out.push(t)
        }
        return out
    }

    readonly property var topic: root.shown.length > 0
                                 ? root.shown[Math.min(root.current,
                                                       root.shown.length - 1)]
                                 : null

    function sectionTitle(id) {
        for (var i = 0; i < root.sections.length; ++i)
            if (root.sections[i].id === id) return root.sections[i].title
        return id
    }

    function titleOf(id) {
        for (var i = 0; i < root.topics.length; ++i)
            if (root.topics[i].id === id) return root.topics[i].title
        return id
    }

    function pushHistory(id) {
        var h = root.history.slice()
        h.push(id)
        root.history = h
    }

    // Go to a topic by id, clearing any search first.
    //
    // The search HAS to be cleared: a see-also link points at a topic that the
    // current filter may well exclude, and moving to an index within a list
    // that does not contain the target lands the reader on an unrelated
    // article. That is worse than a dead link, because it looks like it worked.
    function goTo(id, remember) {
        if (remember && root.topic && root.topic.id !== id)
            root.pushHistory(root.topic.id)
        root.query = ""
        for (var i = 0; i < root.shown.length; ++i) {
            if (root.shown[i].id === id) {
                root.current = i
                list.positionViewAtIndex(i, ListView.Contain)
                return
            }
        }
    }

    function back() {
        if (root.history.length === 0) return
        var h = root.history.slice()
        var id = h.pop()
        root.history = h
        root.goTo(id, false)
    }

    function firstOfSection(id) {
        for (var i = 0; i < root.topics.length; ++i)
            if (root.topics[i].section === id) return root.topics[i].id
        return ""
    }

    // Back to the top on every change of topic. Without this, a long article
    // read to the end leaves the NEXT one scrolled into its middle, which
    // reads as a missing title.
    //
    // Declared here rather than as a Connections inside the article, because a
    // property's own change handler belongs with the property, and the nested
    // version made the ScrollView's contentItem assignment non-deferred.
    onCurrentChanged: if (article.contentItem) article.contentItem.contentY = 0

    onOpened: {
        root.query = ""
        root.current = 0
        root.history = []
        if (root.startAt !== "")
            root.goTo(root.startAt, false)
        else if (root.startSection !== "")
            root.goTo(root.firstOfSection(root.startSection), false)
        searchField.forceActiveFocus()
    }

    background: Rectangle {
        color: Theme.surface
        border.color: Theme.border
        radius: 6
    }

    contentItem: ColumnLayout {
        spacing: 0

        // ---- the header --------------------------------------------------
        RowLayout {
            Layout.fillWidth: true
            Layout.margins: 14
            spacing: 10

            Label {
                text: "GraphVis help"
                color: Theme.text
                font.bold: true
                font.pixelSize: Theme.fontSizeTitle
            }

            Button {
                text: "‹ Back"
                enabled: root.history.length > 0
                onClicked: root.back()
                ToolTip.visible: hovered && enabled
                ToolTip.text: enabled
                              ? "Back to " + root.titleOf(
                                    root.history[root.history.length - 1])
                              : ""
            }

            TextField {
                id: searchField
                Layout.fillWidth: true
                placeholderText: "Search " + root.topics.length + " topics"
                text: root.query
                onTextChanged: { root.query = text; root.current = 0 }
                // Down from the search box moves into the contents rather than
                // making the reader take their hand off the keyboard.
                Keys.onDownPressed: if (root.current < root.shown.length - 1) {
                    root.current += 1
                    list.positionViewAtIndex(root.current, ListView.Contain)
                }
                Keys.onUpPressed: if (root.current > 0) {
                    root.current -= 1
                    list.positionViewAtIndex(root.current, ListView.Contain)
                }
            }

            Label {
                visible: root.query.trim() !== ""
                text: root.shown.length + " match"
                      + (root.shown.length === 1 ? "" : "es")
                color: Theme.textMuted
                font.pixelSize: Theme.fontSizeSmall
            }

            Button { text: "Close"; onClicked: root.close() }
        }

        Rectangle { Layout.fillWidth: true; Layout.preferredHeight: 1; color: Theme.border }

        RowLayout {
            Layout.fillWidth: true
            Layout.fillHeight: true
            spacing: 0

            // ---- the contents ---------------------------------------------
            Rectangle {
                Layout.preferredWidth: 290
                Layout.fillHeight: true
                color: Theme.background

                ListView {
                    id: list
                    anchors.fill: parent
                    anchors.margins: 6
                    clip: true
                    model: root.shown
                    currentIndex: root.current
                    spacing: 0

                    // One delegate, not two. A section header is drawn by the
                    // first topic OF that section rather than by a separate
                    // header row, so filtering can never leave a header
                    // stranded above no topics - the commonest bug in a
                    // grouped list, and one that cannot happen if the header
                    // has no independent existence.
                    delegate: Item {
                        id: row
                        required property int index
                        required property var modelData
                        width: ListView.view ? ListView.view.width : 0
                        implicitHeight: column.implicitHeight

                        readonly property bool startsSection:
                            row.index === 0
                            || root.shown[row.index - 1].section !== row.modelData.section

                        ColumnLayout {
                            id: column
                            width: row.width
                            spacing: 0

                            Label {
                                visible: row.startsSection
                                Layout.fillWidth: true
                                Layout.topMargin: row.index === 0 ? 4 : 12
                                Layout.bottomMargin: 2
                                Layout.leftMargin: 6
                                text: root.sectionTitle(row.modelData.section).toUpperCase()
                                color: Theme.textMuted
                                font.pixelSize: Theme.fontSizeSmall
                                font.bold: true
                                font.letterSpacing: 1
                                elide: Text.ElideRight
                            }

                            ItemDelegate {
                                Layout.fillWidth: true
                                highlighted: row.index === root.current
                                onClicked: {
                                    if (root.topic
                                        && root.topic.id !== row.modelData.id)
                                        root.pushHistory(root.topic.id)
                                    root.current = row.index
                                }
                                contentItem: Label {
                                    text: row.modelData.title
                                    color: Theme.text
                                    wrapMode: Text.WordWrap
                                }
                            }
                        }
                    }
                }
            }

            Rectangle { Layout.preferredWidth: 1; Layout.fillHeight: true; color: Theme.border }

            // ---- the article -----------------------------------------------
            ScrollView {
                id: article
                Layout.fillWidth: true
                Layout.fillHeight: true
                clip: true
                contentWidth: availableWidth

                ColumnLayout {
                    width: article.availableWidth
                    spacing: 8

                    Label {
                        Layout.margins: 16
                        Layout.bottomMargin: 0
                        Layout.fillWidth: true
                        visible: root.topic !== null
                        text: root.topic
                              ? root.sectionTitle(root.topic.section).toUpperCase()
                                + "   ·   "
                                + (root.topic.kind === "task" ? "HOW TO"
                                   : root.topic.kind === "reference" ? "REFERENCE"
                                   : "CONCEPT")
                              : ""
                        color: Theme.textMuted
                        font.pixelSize: Theme.fontSizeSmall
                        font.bold: true
                        font.letterSpacing: 1
                    }

                    Label {
                        Layout.leftMargin: 16
                        Layout.rightMargin: 16
                        Layout.fillWidth: true
                        visible: root.topic !== null
                        text: root.topic ? root.topic.title : ""
                        color: Theme.text
                        font.bold: true
                        font.pixelSize: Theme.fontSizeTitle
                        wrapMode: Text.WordWrap
                    }

                    Label {
                        Layout.leftMargin: 16
                        Layout.rightMargin: 16
                        Layout.fillWidth: true
                        visible: root.topic !== null
                        text: root.topic ? root.topic.body : ""
                        color: Theme.textSecondary
                        textFormat: Text.StyledText
                        wrapMode: Text.WordWrap
                        lineHeight: 1.3
                    }

                    // ---- see also ---------------------------------------
                    Label {
                        Layout.leftMargin: 16
                        Layout.topMargin: 10
                        visible: root.topic !== null
                                 && root.topic.see_also !== undefined
                                 && root.topic.see_also.length > 0
                        text: "SEE ALSO"
                        color: Theme.textMuted
                        font.pixelSize: Theme.fontSizeSmall
                        font.bold: true
                        font.letterSpacing: 1
                    }

                    Flow {
                        Layout.leftMargin: 16
                        Layout.rightMargin: 16
                        Layout.bottomMargin: 16
                        Layout.fillWidth: true
                        spacing: 6
                        visible: root.topic !== null
                                 && root.topic.see_also !== undefined
                                 && root.topic.see_also.length > 0

                        Repeater {
                            model: root.topic && root.topic.see_also
                                   ? root.topic.see_also : []
                            delegate: Button {
                                required property var modelData
                                text: root.titleOf(modelData)
                                flat: true
                                onClicked: root.goTo(modelData, true)
                            }
                        }
                    }

                    Label {
                        Layout.margins: 16
                        Layout.fillWidth: true
                        visible: root.topic === null
                        text: "Nothing in the help matches \"" + root.query
                              + "\".<br><br>Try a word from the problem rather "
                              + "than the name of the control - <i>blank</i>, "
                              + "<i>slow</i>, <i>squashed</i>, "
                              + "<i>colourblind</i>, <i>log</i>, <i>journal</i>."
                        textFormat: Text.StyledText
                        color: Theme.textMuted
                        wrapMode: Text.WordWrap
                    }

                    Item { Layout.fillHeight: true }
                }
            }
        }
    }
}
