"""Catalogue entries for the engine expansion, batches 1 to 19.

Idempotent: keyed by (engine, scale), replaced rather than appended. Run
tools/add_scale_variants.py afterwards to give the new axis engines their scale
variants, the same way every other engine got them.

    python3 tools/add_batch1_engines.py [config/graph_catalogue.json]
"""
import json
import pathlib
import sys

path = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else "config/graph_catalogue.json")
doc = json.loads(path.read_text(encoding="utf-8"))
cats = doc["categories"]

# (category, name, engine, description). Categories are existing ones: a new
# engine that needs a new category usually means it has been filed wrong.
NEW = [
    ("Statistical Inference & Effect", "lorenz", "Lorenz Curve",
     "Cumulative share of the total against cumulative share of the population, with the Gini coefficient"),
    ("Statistical Inference & Effect", "concentration", "Concentration Curve",
     "Cumulative share of an outcome against population ranked by a second variable"),
    ("Data Distribution Plots", "rankabundance", "Rank-Abundance Curve",
     "Value against rank, commonest first, on a log axis — dominance versus evenness"),
    ("Model Evaluation", "scree", "Scree Plot",
     "Eigenvalues by component with the cumulative share over the top"),
    ("Model Evaluation", "predictionerror", "Prediction Error Plot",
     "Observed against predicted with the identity line, the best fit and R²"),
    ("Model Evaluation", "learningcurve", "Learning Curve",
     "Training and validation score against training-set size — the gap is overfitting"),
    ("Model Evaluation", "validationcurve", "Validation Curve",
     "Training and validation score against one hyperparameter"),
    ("Model Evaluation", "discrimination", "Discrimination Threshold",
     "Precision, recall, F1 and queue rate against the decision threshold"),
    ("Model Evaluation", "silhouette", "Silhouette Plot",
     "One bar per observation, sorted within its cluster, with the overall mean"),
    ("Model Evaluation", "elbow", "Elbow Plot",
     "Clustering score against number of clusters, with the knee found by maximum chord distance"),
    ("Clinical & Meta-analysis", "radialplot", "Radial Plot",
     "Galbraith plot: standardised effect against precision, with the pooled slope"),
    ("Clinical & Meta-analysis", "labbe", "L'Abbé Plot",
     "Treated-arm rate against control-arm rate, one point per study"),
    ("Clinical & Meta-analysis", "caterpillar", "Caterpillar Plot",
     "A forest plot sorted by estimate, so the shape of the evidence is visible"),
    ("Clinical & Meta-analysis", "cumulativemeta", "Cumulative Meta-Analysis",
     "The pooled estimate recomputed as each study is added, with its interval"),
    ("Clinical & Meta-analysis", "nelsonaalen", "Nelson-Aalen Cumulative Hazard",
     "Cumulative hazard against time, where a constant hazard is a straight line"),
    ("Clinical & Meta-analysis", "cumincidence", "Cumulative Incidence",
     "Cumulative incidence against time, from event times and an event flag"),
    ("Clinical & Meta-analysis", "decisioncurve", "Decision Curve",
     "Net benefit against threshold probability, with treat-all and treat-none"),
    ("Maintenance & Reliability", "bathtub", "Bathtub Curve",
     "Hazard rate against age — infant mortality, useful life and wear-out"),
    ("Maintenance & Reliability", "duane", "Duane Plot",
     "Cumulative MTBF against cumulative operating time on log-log axes, with the growth slope"),
    ("Maintenance & Reliability", "mcf", "Mean Cumulative Function",
     "Mean cumulative repairs per unit against age, for repairable systems"),

    # ---- batch 2: engineering
    ("Fluid & Field Dynamics", "moody", "Moody Diagram",
     "Darcy friction factor against Reynolds number over the Colebrook-White roughness family"),
    ("Fluid & Field Dynamics", "pumpcurve", "Pump Performance Curve",
     "Head against flow with the system resistance curve and the duty point marked"),
    ("Materials & Chemistry", "stribeck", "Stribeck Curve",
     "Friction coefficient against Hersey number — boundary, mixed and hydrodynamic regimes"),
    ("Materials & Chemistry", "haigh", "Haigh Diagram",
     "Alternating against mean stress with the Goodman, Gerber and Soderberg envelopes"),
    ("Materials & Chemistry", "dadn", "Crack Growth Rate",
     "da/dN against dK on log-log axes, with the Paris exponent and coefficient fitted"),
    ("Materials & Chemistry", "strainlife", "Strain-Life Curve",
     "Strain amplitude against reversals to failure"),
    ("Materials & Chemistry", "larsonmiller", "Larson-Miller Curve",
     "Stress against the Larson-Miller parameter, collapsing creep-rupture tests onto one curve"),
    ("Advanced Line & Signal Plots", "campbell", "Campbell Diagram",
     "Natural frequencies against shaft speed with the engine-order rays"),
    ("Advanced Line & Signal Plots", "shaftorbit", "Shaft Orbit",
     "The journal centre's path from a pair of proximity probes — the shape is the diagnosis"),
    ("Spatial & Specialized", "plasticity", "Plasticity Chart",
     "Plasticity index against liquid limit over Casagrande's A-line and U-line"),
    ("Spatial & Specialized", "psd", "Particle Size Distribution",
     "Percent finer against grain size on a reversed log axis, with D10, D30 and D60"),
    ("Signals & RF", "nichols", "Nichols Chart",
     "Open-loop gain against phase, with the critical point at −180°, 0 dB"),
    ("Signals & RF", "polezero", "Pole-Zero Map",
     "Poles and zeros on the complex plane with the stability boundary"),
    ("Energy & Building Services", "pvnose", "P-V Nose Curve",
     "Bus voltage against transferred power, with the voltage-collapse point"),
    ("Aviation & Flight", "airfoilcp", "Airfoil Cp Distribution",
     "Pressure coefficient along the chord, y axis inverted as convention requires"),

    # ---- batch 3: chemistry, earth science, physics, medicine
    ("Materials & Chemistry", "lineweaver", "Lineweaver-Burk Plot",
     "1/v against 1/[S] with Vmax and Km read off the fitted line"),
    ("Materials & Chemistry", "eadie", "Eadie-Hofstee Plot",
     "v against v/[S] — the same constants with the error placed differently"),
    ("Materials & Chemistry", "haneswoolf", "Hanes-Woolf Plot",
     "[S]/v against [S] — the third rearrangement, and the best conditioned of them"),
    ("Materials & Chemistry", "scatchard", "Scatchard Plot",
     "Bound/free against bound; slope −1/Kd, x intercept the number of sites"),
    ("Spectroscopy & Chromatography", "vandeemter", "van Deemter Plot",
     "Plate height against velocity with the A + B/u + Cu fit and its optimum"),
    ("Materials & Chemistry", "bet", "BET Plot",
     "The BET transform over the 0.05–0.35 linear region, with monolayer capacity"),
    ("Materials & Chemistry", "jobplot", "Job Plot",
     "Signal against mole fraction; the maximum gives the complex stoichiometry"),
    ("Earth & Ocean Science", "gutenberg", "Gutenberg-Richter Plot",
     "Log cumulative event count against magnitude, with the b-value fitted"),
    ("Earth & Ocean Science", "doublemass", "Double-Mass Curve",
     "Cumulative station total against a reference; a slope change is an inhomogeneity"),
    ("Earth & Ocean Science", "hodograph", "Hodograph",
     "Wind u against v traced with height, with speed rings"),
    ("Clinical & Meta-analysis", "flowvolume", "Flow-Volume Loop",
     "Flow against volume as a closed loop — the shape is the diagnosis"),
    ("Clinical & Meta-analysis", "pvloop", "Pressure-Volume Loop",
     "Ventricular pressure against volume; the enclosed area is stroke work"),
    ("Signals & RF", "allan", "Allan Deviation",
     "Overlapping Allan deviation against averaging time on log-log axes"),
    ("Signals & RF", "paschen", "Paschen Curve",
     "Breakdown voltage against pressure × gap, with the Paschen minimum"),
    ("Spatial & Specialized", "phasefold", "Phase-Folded Light Curve",
     "Flux against phase after folding on a trial period, drawn over two cycles"),
    ("Spatial & Specialized", "ocdiagram", "O-C Diagram",
     "Observed minus computed event time against epoch, with the ephemeris fitted"),

    # ---- batch 4: model interpretation, diagnostics, decision analysis
    ("Model Evaluation", "pdp", "Partial Dependence Plot",
     "Average predicted response as one feature is varied"),
    ("Model Evaluation", "ice", "ICE Plot",
     "One curve per observation, with the partial dependence as their average"),
    ("Statistical & Diagnostic Plots", "influence", "Influence Plot",
     "Studentised residual against leverage, with the conventional cut-offs"),
    ("Statistical & Diagnostic Plots", "addedvar", "Added-Variable Plot",
     "Partial regression: the slope of this scatter is the coefficient in the full model"),
    ("Statistical & Diagnostic Plots", "interaction", "Interaction Plot",
     "Cell means across one factor, one line per level of a second"),
    ("Statistical Inference & Effect", "tornado", "Tornado Diagram",
     "Each input's low-to-high swing around the base case, sorted longest first"),
    ("Presentation & Comparison", "frontier", "Efficient Frontier",
     "Return against risk with the non-dominated frontier drawn through the cloud"),
    ("Time Series & Trend", "fanchart", "Fan Chart",
     "A forecast as nested probability bands widening into the future"),
    ("Time Series & Trend", "snailtrail", "Snail Trail",
     "Trailing risk against trailing return, joined in time order"),
    ("Clinical & Meta-analysis", "ceplane", "Cost-Effectiveness Plane",
     "Incremental cost against incremental effect with the willingness-to-pay ray"),
    ("Clinical & Meta-analysis", "ceac", "Acceptability Curve",
     "Probability an option is cost-effective, against willingness to pay"),
    ("Clinical & Meta-analysis", "lasagna", "Lasagna Plot",
     "A subject-by-time raster — the readable alternative to a spaghetti plot"),
    ("Clinical & Meta-analysis", "swimmer", "Swimmer Plot",
     "One lane per subject from start to stop, longest at the top"),

    # ---- batch 5: electrochemistry, bioprocess kinetics, energy, structures
    ("Electrochemical & Bioprocess", "tafel", "Tafel Plot",
     "Overpotential against log current density, each branch fitted for its slope and exchange current"),
    ("Electrochemical & Bioprocess", "cyclicvoltammogram", "Cyclic Voltammogram",
     "Current against potential as a swept loop, with the peak separation and current ratio"),
    ("Electrochemical & Bioprocess", "levich", "Levich Plot",
     "Limiting current against the square root of rotation rate, through the origin"),
    ("Electrochemical & Bioprocess", "koutecky", "Koutecky-Levich Plot",
     "Reciprocal current against reciprocal root rotation; the intercept is the kinetic current"),
    ("Electrochemical & Bioprocess", "randles", "Randles-Sevcik Plot",
     "Peak current against the square root of scan rate — diffusion control is a straight line"),
    ("Electrochemical & Bioprocess", "monod", "Monod Growth Curve",
     "Specific growth rate against substrate, with µmax and Ks fitted"),
    ("Electrochemical & Bioprocess", "haldane", "Substrate Inhibition Curve",
     "Haldane kinetics: growth rate rises, peaks and falls, with Ki and the optimum concentration"),
    ("Energy & Building Services", "ragone", "Ragone Plot",
     "Specific energy against specific power on log axes, over the constant-discharge-time diagonals"),
    ("Energy & Building Services", "ivcurve", "I-V Curve",
     "Photovoltaic current against voltage with the maximum-power rectangle and fill factor"),
    ("Energy & Building Services", "degreeday", "Degree-Day Signature",
     "Metered energy against outside temperature, with the balance point fitted by change-point search"),
    ("Energy & Building Services", "macc", "Abatement Cost Curve",
     "Measures cheapest first as blocks whose width is the saving and height the cost per unit"),
    ("Tensor & Structure Analysis", "mohr", "Mohr's Circle",
     "A stress state as a circle, with the principal stresses, maximum shear and principal angle"),
    ("Civil & Structural", "pminteraction", "P-M Interaction Diagram",
     "The axial-load and moment capacity envelope, closed, with the balanced point marked"),
    ("Civil & Structural", "pushover", "Pushover Capacity Curve",
     "Base shear against roof displacement with the equal-area bilinear idealisation and ductility"),
    ("Civil & Structural", "responsespectrum", "Response Spectrum",
     "Peak response against period on a log axis, one curve per damping ratio"),
    ("Civil & Structural", "consolidation", "Consolidation Curve",
     "Settlement against log time with Casagrande's construction and t50"),
    ("Spectral", "lombscargle", "Lomb-Scargle Periodogram",
     "Power against frequency for unevenly sampled data, which an FFT cannot take"),
    ("Categorical & Set Views", "waffle", "Waffle Chart",
     "A hundred squares apportioned by largest remainder, so the counts read exactly"),

    # ---- batch 6: regression diagnostics, signal structure, multivariate
    ("Statistical & Diagnostic Plots", "cooksdistance", "Cook's Distance Plot",
     "Influence by observation, with the 4/n screening threshold"),
    ("Statistical & Diagnostic Plots", "scalelocation", "Scale-Location Plot",
     "Root standardised residual against fitted value — flat means constant variance"),
    ("Statistical & Diagnostic Plots", "partialresidual", "Partial Residual Plot",
     "The residual with one predictor's contribution added back; curvature means the linear term is wrong"),
    ("Data Reduction & Interpolation", "savgol", "Savitzky-Golay Smoothing",
     "Polynomial smoothing over a fixed window, which keeps peak height and width"),
    ("Data Reduction & Interpolation", "lowesstrend", "LOWESS Trend",
     "A locally weighted trend through a scatter, adapting to uneven sampling"),
    ("Signal Processing Plots", "pacf", "Partial Autocorrelation",
     "Correlation at each lag with the shorter lags removed, by Durbin-Levinson"),
    ("Time Series & Trend", "stl", "Seasonal Decomposition",
     "Observed, trend, repeating cycle and remainder, with the period found or given"),
    ("Time Series & Trend", "subseries", "Seasonal Subseries Plot",
     "One line per position in the cycle, so drift within a season is visible"),
    ("Advanced Line & Signal Plots", "recurrence", "Recurrence Plot",
     "A mark wherever the record revisits an earlier state — diagonals mean deterministic structure"),
    ("Spectral & Signal Imaging", "scalogram", "Wavelet Scalogram",
     "Where the frequency content sits in time, by Morlet wavelet"),
    ("Spectral", "coherence", "Coherence Spectrum",
     "How much of one signal each frequency of another explains, averaged over Welch segments"),
    ("Signals & RF", "bode", "Bode Plot",
     "Loop gain and phase against frequency, with the 0 dB crossover"),
    ("Quality, Process & Reliability", "occurve", "Operating Characteristic Curve",
     "Probability a sampling plan accepts a lot, against how defective the lot is"),
    ("Electrochemical & Bioprocess", "cottrell", "Cottrell Plot",
     "Current against 1/sqrt(time); a straight line through the origin means diffusion control"),
    ("Electrochemical & Bioprocess", "coulombic", "Coulombic Efficiency Trend",
     "Efficiency by cycle with the cumulative mean and the trend across cycles"),
    ("Multivariate Plots", "biplot", "Biplot",
     "Observations and variables on one pair of principal components"),
    ("Multivariate Plots", "starglyph", "Star Glyph Plot",
     "One small radar per observation on a grid, so shapes can be matched by eye"),
    ("Scatter & Bubble Charts", "sunflower", "Sunflower Plot",
     "A petal per observation where points coincide, so density shows without hiding points"),

    # ---- batch 7: geochronology, hydrology, thermal analysis, spectroscopy,
    # rheology, acoustics, pharmacokinetics and control
    ("Earth & Ocean Science", "concordia", "Concordia Diagram",
     "U-Pb ratios against the concordia curve, with the discordia chord and its upper intercept"),
    ("Earth & Ocean Science", "isochron", "Isochron Plot",
     "Daughter against parent, both over a stable isotope; the slope is the age and the intercept the initial ratio"),
    ("Earth & Ocean Science", "harker", "Harker Diagram",
     "Every oxide against silica, with the fractionation trend fitted for each"),
    ("Earth & Ocean Science", "spider", "Normalised Spider Diagram",
     "Samples divided element by element by a reference composition, on a log axis"),
    ("Earth & Ocean Science", "keeling", "Keeling Plot",
     "Isotopic composition against one over concentration; the intercept is the source signature"),
    ("Earth & Ocean Science", "idf", "IDF Curve",
     "Rainfall intensity against duration on log-log axes, one curve per return period"),
    ("Materials & Chemistry", "vanthoff", "Van 't Hoff Plot",
     "ln K against 1/T, with the reaction enthalpy and entropy read off the line"),
    ("Spectroscopy & Chromatography", "tauc", "Tauc Plot",
     "(alpha h v)^2 against photon energy, with the band gap from the steepest tangent"),
    ("Spectroscopy & Chromatography", "sternvolmer", "Stern-Volmer Plot",
     "I0/I against quencher concentration, with the Stern-Volmer constant fitted"),
    ("Materials & Chemistry", "tga", "TGA / DTG Curve",
     "Mass against temperature with its derivative over the top and the extrapolated onset"),
    ("Materials & Chemistry", "dsc", "DSC Thermogram",
     "Heat flow against temperature with the integration baseline and the peak area"),
    ("Materials & Chemistry", "creep", "Creep Curve",
     "Strain against time under load, with the minimum creep rate fitted in the secondary stage"),
    ("Materials & Chemistry", "mastercurve", "Master Curve (TTS)",
     "Isotherms shifted horizontally until they superpose, with the shift factor for each"),
    ("Materials & Chemistry", "flowcurve", "Rheology Flow Curve",
     "Shear stress against shear rate with Herschel-Bulkley fitted: yield stress, consistency and index"),
    ("Signals & RF", "octaveband", "Octave Band Spectrum",
     "Narrowband levels summed in energy into third-octave bands, with the A-weighted overall"),
    ("Clinical & Meta-analysis", "pkprofile", "Pharmacokinetic Profile",
     "Concentration against time with Cmax, Tmax, the trapezoidal AUC and the terminal half-life"),
    ("Presentation & Comparison", "yieldcurve", "Yield Curve",
     "Yield against maturity, one curve per date, with the long-short spread and any inversion flagged"),
    ("Signals & RF", "nyquiststability", "Nyquist Stability Plot",
     "The open-loop locus against the critical point, with the gain and phase margins"),

    # ---- batch 8: geotechnics, flight performance, process integration,
    # metrology, epidemiology and remote sensing
    ("Civil & Structural", "proctor", "Proctor Compaction Curve",
     "Dry density against moisture with the optimum fitted and the zero-air-voids limit"),
    ("Civil & Structural", "mohrcoulomb", "Mohr-Coulomb Envelope",
     "Shear at failure against normal stress, giving the cohesion and the friction angle"),
    ("Civil & Structural", "influenceline", "Influence Line",
     "A response against the position of a unit load, with the worst position marked"),
    ("Aviation & Flight", "balancedfield", "Balanced Field Length",
     "Accelerate-stop against accelerate-go; where they cross is the balanced field"),
    ("Aviation & Flight", "specificrange", "Specific Range",
     "Distance per unit of fuel against weight, with the peak refined between samples"),
    ("Energy & Building Services", "pinch", "Composite Curves (Pinch)",
     "Hot and cold composites offset to the minimum approach, giving the pinch and both utilities"),
    ("Electrochemical & Bioprocess", "rtd", "Residence Time Distribution",
     "E(t) from a tracer pulse, with the mean, the variance and the tanks-in-series number"),
    ("Signals & RF", "harmonics", "Harmonic Spectrum",
     "Magnitude by harmonic order with the total harmonic distortion computed from it"),
    ("Signals & RF", "soundstats", "Sound Level Statistics",
     "Level against percentage of time exceeded, with L10, L50, L90 and the energy-average Leq"),
    ("Spectroscopy & Chromatography", "beamcaustic", "Beam Caustic",
     "Beam radius through a focus, fitted as a parabola in the square for the waist and divergence"),
    ("Quality, Process & Reliability", "youden", "Youden Plot",
     "Two materials measured by every laboratory, separating random scatter from systematic bias"),
    ("Quality, Process & Reliability", "leveyjennings", "Levey-Jennings Chart",
     "Control results against the mean and its deviation bands, with the Westgard 1-3s and 2-2s counts"),
    ("Statistical Inference & Effect", "speciesaccum", "Species Accumulation Curve",
     "Species found against sampling effort, with the Chao1 estimate of what is left"),
    ("Clinical & Meta-analysis", "epicurve", "Epidemic Curve",
     "Cases by date of onset with a centred moving average, so the peak is not reported late"),
    ("Clinical & Meta-analysis", "rteffective", "Effective Reproduction Number",
     "R from the growth rate of the case series and a stated generation interval"),
    ("Model Evaluation", "cumulativegain", "Cumulative Gain Chart",
     "Positives captured against population contacted, with the random and perfect baselines"),
    ("Electrochemical & Bioprocess", "ratkowsky", "Ratkowsky Square-Root Plot",
     "Square root of growth rate against temperature, extrapolated to the minimum growth temperature"),
    ("Earth & Ocean Science", "phenology", "Phenology Curve",
     "A vegetation index through the year with green-up, peak and senescence at half amplitude"),

    # ---- batch 9: scattering, thermal kinetics, astronomy, radio, and three
    # decision curves from operations and trials
    ("Spectroscopy & Chromatography", "guinier", "Guinier Plot",
     "ln I against q squared, with the radius of gyration and the qRg range the fit actually used"),
    ("Spectroscopy & Chromatography", "kratky", "Kratky Plot",
     "q squared times intensity against q, where a compact particle is a bell and a chain is not"),
    ("Materials & Chemistry", "hill", "Hill Plot",
     "Log bound over unbound against log ligand, giving the Hill coefficient and half occupancy"),
    ("Materials & Chemistry", "ellingham", "Ellingham Diagram",
     "Free energy of oxide formation against temperature, over the carbon monoxide line"),
    ("Materials & Chemistry", "kissinger", "Kissinger Plot",
     "How the peak temperature moves with heating rate, giving the activation energy"),
    ("Materials & Chemistry", "avrami", "Avrami Plot",
     "Double log of the untransformed fraction against log time, giving the Avrami exponent"),
    ("Energy & Building Services", "wilson", "Wilson Plot",
     "1/U against velocity to the minus 0.8, separating fouling from the tube-side film"),
    ("Materials & Chemistry", "vankrevelen", "Van Krevelen Diagram",
     "H/C against O/C with the dehydration, decarboxylation and demethanation paths walked out"),
    ("Spatial & Specialized", "hrdiagram", "Hertzsprung-Russell Diagram",
     "Magnitude against colour with both astronomical inversions, and the observed ridge line"),
    ("Spatial & Specialized", "rotationcurve", "Rotation Curve",
     "Orbital speed against radius, against the Keplerian curve anchored at the peak"),
    ("Spatial & Specialized", "hubble", "Hubble Diagram",
     "Recession speed against distance through the origin, with H0 and the Hubble time"),
    ("Signals & RF", "constellation", "Constellation Diagram",
     "Received symbols against the best-fitting square QAM grid, with the error vector magnitude"),
    ("Signals & RF", "groupdelay", "Group Delay",
     "The slope of the unwrapped phase, with the mean delay and the ripple across the band"),
    ("Earth & Ocean Science", "windprofile", "Wind Profile (Log Law)",
     "Wind speed against log height, giving the friction velocity and the roughness length"),
    ("Presentation & Comparison", "experiencecurve", "Experience Curve",
     "Unit cost against cumulative production, reported as the learning rate per doubling"),
    ("Logistics & Infrastructure", "eoq", "EOQ Cost Curve",
     "Ordering and holding cost against order quantity, with the cheapest order and their crossing"),
    ("Quality, Process & Reliability", "halfnormal", "Half-Normal Plot",
     "Absolute effects against half-normal quantiles, with Lenth's pseudo standard error"),
    ("Clinical & Meta-analysis", "responsewaterfall", "Response Waterfall",
     "Best change from baseline per patient, sorted, against the RECIST thresholds"),

    # ---- batch 10: open-channel and process hydraulics, power systems,
    # imaging, radiation, exercise physiology, traffic, sequential decisions
    ("Fluid & Field Dynamics", "specificenergy", "Specific Energy Diagram",
     "Depth against specific energy at a fixed discharge, with the critical depth computed"),
    ("Energy & Building Services", "ntueffectiveness", "NTU-Effectiveness Curve",
     "Measured effectiveness against NTU, over the counterflow limit for the same capacity ratio"),
    ("Fluid & Field Dynamics", "operatingpoint", "Pump Operating Point",
     "Pump curve against system curve, with the duty point where they cross"),
    ("Energy & Building Services", "duckcurve", "Duck Curve (Net Load)",
     "Demand minus renewables through the day, with the trough, the peak and the steepest ramp"),
    ("Energy & Building Services", "coordination", "Protection Coordination Curve",
     "Time-current curves per device on log-log axes, with the tightest coordination interval"),
    ("Spectral & Signal Imaging", "mtf", "MTF Curve",
     "Contrast against spatial frequency, with MTF50 and MTF10 interpolated"),
    ("Materials & Chemistry", "decayfit", "Radioactive Decay Fit",
     "Activity against time on a log ordinate, with the half-life and decay constant fitted"),
    ("Materials & Chemistry", "attenuation", "Attenuation Curve",
     "Transmitted intensity against absorber thickness, giving mu and the half-value layer"),
    ("Clinical & Meta-analysis", "depthdose", "Depth-Dose Curve",
     "Dose against depth with the peak and the distal R90 and R80 depths"),
    ("Clinical & Meta-analysis", "criticalpower", "Critical Power Curve",
     "Power against one over duration, giving the critical power and the work above it"),
    ("Clinical & Meta-analysis", "lactate", "Lactate Threshold Curve",
     "Blood lactate against work rate, with the fixed 4 mmol crossing and the D-max point"),
    ("Signals & RF", "halfpower", "Half-Power Bandwidth",
     "A resonance with its half-power points, giving the quality factor and the damping ratio"),
    ("Logistics & Infrastructure", "cumulativecount", "Cumulative Vehicle Count",
     "Cumulative arrivals against departures, giving the longest queue and the total delay"),
    ("Presentation & Comparison", "cohortretention", "Cohort Retention Curve",
     "Retention against age rather than calendar date, so cohorts can be compared"),
    ("Presentation & Comparison", "bassdiffusion", "Bass Diffusion Curve",
     "Cumulative adoption with the Bass model fitted: innovation, imitation and market size"),
    ("Quality, Process & Reliability", "pareto", "Pareto Chart",
     "Counts by category largest first with the running share and the 80% line"),
    ("Statistical Inference & Effect", "powercurve", "Statistical Power Curve",
     "Power against sample size per effect size, with the size needed for 80% power"),
    ("Quality, Process & Reliability", "sprt", "Sequential Test Boundaries",
     "The running log-likelihood ratio against Wald's two stopping boundaries"),

    # ---- batch 11: separation science, adsorption, molecular biology,
    # magnetics, drives, antennas, soil physics, long-memory statistics
    ("Spectroscopy & Chromatography", "chrompeaks", "Chromatogram Peak Metrics",
     "A chromatogram with plate count, tailing factor and resolution computed from it"),
    ("Materials & Chemistry", "langmuir", "Langmuir Isotherm",
     "Ce/qe against Ce, giving the saturation capacity, the affinity and the separation factor"),
    ("Materials & Chemistry", "zeta", "Zeta Potential Curve",
     "Surface charge against pH with the isoelectric point and the stability bands"),
    ("Materials & Chemistry", "distillation", "Distillation Curve",
     "Boiling temperature against volume recovered, with T10, T50 and T90"),
    ("Clinical & Meta-analysis", "qpcr", "qPCR Standard Curve",
     "Threshold cycle against log quantity, reported as amplification efficiency"),
    ("Clinical & Meta-analysis", "melting", "Melting Curve (Tm)",
     "Fluorescence with its negative derivative over it, so Tm is the derivative peak"),
    ("Electrochemical & Bioprocess", "growthrate", "Growth Rate (OD)",
     "Optical density on a log ordinate with the growth rate fitted in the exponential window"),
    ("Clinical & Meta-analysis", "percentile", "Growth Percentile Chart",
     "A measurement against age with percentile bands taken from this population"),
    ("Materials & Chemistry", "hysteresis", "Hysteresis Loop (B-H)",
     "Flux density against field, with remanence, coercivity and the loss per cycle"),
    ("Energy & Building Services", "torquespeed", "Torque-Speed Curve",
     "Motor torque against load torque, with the starting, breakdown and operating points"),
    ("Signals & RF", "pattern", "Radiation Pattern",
     "Gain against bearing with the beamwidth, the front-to-back ratio and the sidelobe level"),
    ("Earth & Ocean Science", "retention", "Soil Water Retention Curve",
     "Water content against log suction, with field capacity, wilting point and available water"),
    ("Signal Processing Plots", "dfa", "Detrended Fluctuation Analysis",
     "Fluctuation against window size on log-log axes, giving the scaling exponent"),
    ("Clinical & Meta-analysis", "poincare", "Poincare Plot",
     "Each interval against the next, with the SD1 and SD2 ellipse"),
    ("Logistics & Infrastructure", "kingman", "Kingman Queue Curve",
     "Waiting time against utilisation, over the rho/(1-rho) reference"),
    ("Logistics & Infrastructure", "littleslaw", "Little's Law Check",
     "Work in progress against arrival rate times lead time, tested against the identity"),
    ("Presentation & Comparison", "burndown", "Burndown Chart",
     "Work remaining over time with the straight-line reference and the projected finish"),
    ("Statistical Inference & Effect", "confidenceband", "Regression Confidence Band",
     "A fit with the band for the line and the wider band for the next observation"),

    # ---- batch 12, the last of the rewrites: diffuse reflectance, adsorption,
    # dielectrics, titration, thermal conductivity, measurement-system
    # variation, tolerance, rare events, repeated measures, hydrographs, step
    # response, jitter, well testing and thermal kinetics
    ("Spectroscopy & Chromatography", "kubelkamunk", "Kubelka-Munk Plot",
     "Diffuse reflectance turned into an absorption-like function, with the band gap where the axis allows"),
    ("Materials & Chemistry", "freundlich", "Freundlich Isotherm",
     "log qe against log Ce, giving Kf and 1/n - the companion to Langmuir"),
    ("Materials & Chemistry", "colecole", "Cole-Cole Plot",
     "Imaginary against real permittivity with a fitted arc, its intercepts and its depression"),
    ("Materials & Chemistry", "conductometric", "Conductometric Titration",
     "Conductivity against titrant with both straight branches fitted and their crossing"),
    ("Materials & Chemistry", "hotwire", "Hot-Wire Conductivity",
     "Temperature rise against ln time, giving the thermal conductivity from the slope"),
    ("Quality, Process & Reliability", "multivari", "Multi-Vari Chart",
     "Readings grouped by part and coloured by operator, with the variation split three ways"),
    ("Statistical Inference & Effect", "tolerance", "Tolerance Interval Plot",
     "Limits containing 95% of the population with 95% confidence, beside the interval for the mean"),
    ("Statistical Process Control", "rareevent", "Rare-Event Interval Chart",
     "Time between rare events with exponential limits, so a cluster shows as a short gap"),
    ("Clinical & Meta-analysis", "spaghetti", "Spaghetti Plot",
     "Every subject's own trajectory with the mean over the top"),
    ("Earth & Ocean Science", "unithydrograph", "Unit Hydrograph",
     "A storm hydrograph with baseflow separated, giving the peak, time to peak and runoff volume"),
    ("Earth & Ocean Science", "recession", "Recession Curve Analysis",
     "The falling limb on a log ordinate, giving the recession constant and the halving time"),
    ("Signals & RF", "stepmetrics", "Step Response Metrics",
     "A step response with the rise time, overshoot and settling time measured from the settled value"),
    ("Signals & RF", "jitterbathtub", "Jitter Bathtub",
     "Bit error rate against sampling position, with both walls extrapolated in Q to 1e-12"),
    ("Fluid & Field Dynamics", "pressurederivative", "Pressure Derivative Plot",
     "A well test with the Bourdet derivative and the radial-flow plateau located"),
    ("Materials & Chemistry", "isoconversional", "Isoconversional Plot",
     "Activation energy against conversion by Ozawa-Flynn-Wall, so a changing mechanism shows"),

    # ---- batch 13: the first engine with a painter of its own
    ("Earth & Ocean Science", "skewt", "Skew-T Log-P",
     "A sounding on skewed logarithmic axes with dry and saturated adiabats, mixing ratios, the parcel path, LCL, CAPE and CIN"),

    # ---- batch 14: the Skew-T's three siblings. Same sounding, same parcel,
    # same background families, same energy integrals. They differ only in
    # where a temperature and a pressure land on the page - and each of the
    # three differences is the reason somebody prefers that chart to the
    # others, so all three are offered rather than one of them.
    ("Earth & Ocean Science", "emagram", "Emagram",
     "A sounding with vertical isotherms - the oldest of the thermodynamic diagrams and the easiest to read a temperature off"),
    ("Earth & Ocean Science", "stuve", "Stuve Diagram",
     "A sounding against pressure to the power R/cp, the scale on which the dry adiabats come out straight"),
    ("Earth & Ocean Science", "tephigram", "Tephigram",
     "A sounding against log potential temperature, rotated, so that area is proportional to energy and CAPE can be judged by eye"),

    # ---- batch 15: four more that needed geometry of their own.
    ("Earth & Ocean Science", "stiff", "Stiff Diagram",
     "One water is one shape: six major ions in milliequivalents, cations left and anions right, on one scale so shapes can be compared"),
    ("Logistics & Infrastructure", "arcdiagram", "Arc Diagram",
     "An edge list on a line with the edges as arcs above it - for a graph whose node order already means something"),
    ("Flow, Network & Composition", "icicle", "Icicle Plot",
     "A hierarchy as nested bars from node, parent and own-value columns, with depth on its own axis"),
    ("Flow, Network & Composition", "flamegraph", "Flame Graph",
     "The same nested bars drawn upward with siblings sorted, the form a profiler prints"),
    ("Spatial & Specialized", "voronoi", "Voronoi Diagram",
     "The region nearer to each site than to any other, shaded by cell area so thinly sampled ground stands out"),

    # ---- batch 16
    ("Spatial & Specialized", "durov", "Durov Diagram",
     "The Piper's six ions projected into a square, where a mixing line between two waters is straight"),
    ("Civil & Structural", "tripartite", "Tripartite Response Spectrum",
     "Period against pseudo-velocity on log-log, with constant displacement and constant acceleration as straight families - four quantities on two axes"),

    # ---- batch 17
    ("Categorical & Set Views", "cladogram", "Cladogram",
     "A tree from node, parent and branch-length columns, drawn square so the horizontal run of a branch is its length"),
    ("Time Series & Trend", "streamgraph", "Streamgraph",
     "Stacked bands on a free baseline, so a band's own shape survives the ones under it; thickness is the value and there is no y scale"),

    # ---- batch 18
    ("Contour Plots", "ternarycontour", "Ternary Contour",
     "A quantity measured over three components, contoured on the Delaunay triangulation of the samples themselves - linear in each triangle and nothing outside the hull"),

    # ---- batch 19
    ("Flow, Network & Composition", "alluvial", "Alluvial Diagram",
     "An edge list as a flow through stages, the stages computed by longest path; a node is as tall as the larger of what enters and what leaves it"),
    ("Logistics & Infrastructure", "hive", "Hive Plot",
     "A network on three radial axes, every node placed by degree - so the same edge list always draws the same figure and two graphs can be compared"),
]

by_name = {c["name"]: c for c in cats}
missing = sorted({c for c, *_ in NEW if c not in by_name})
if missing:
    raise SystemExit("no such categories: %s" % ", ".join(missing))

added = 0
for category, name, engine, description in NEW:
    cat = by_name[category]
    # Replaced IN PLACE when the entry is already there, appended only when it
    # is new. Removing and re-appending would have been simpler and was wrong:
    # add_scale_variants.py appends an engine's variants to the end of the
    # category, so a rerun of this script moved the base entry down PAST its own
    # variants and the file changed again - the pipeline needed two passes to
    # stop moving, which is not what idempotent means. Nothing was lost by it;
    # a catalogue that differs from itself is just impossible to review.
    at = next((i for i, e in enumerate(cat["entries"])
               if e["engine"] == engine and e.get("scale") is None), None)
    entry = {
        "category": category,
        "name": name,
        "engine": engine,
        "scale": None,
        "advanced": False,
        "description": description,
        "preview": "",
        "thumbnail": "",
    }
    if at is None:
        cat["entries"].append(entry)
    else:
        cat["entries"][at] = entry
    added += 1

doc["category_count"] = len(cats)
doc["entry_count"] = sum(len(c["entries"]) for c in cats)
doc["engine_count"] = len({e["engine"] for c in cats for e in c["entries"]})
path.write_text(json.dumps(doc, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
print("batches 1-19: %d engines; catalogue now %d entries / %d engines / %d categories"
      % (added, doc["entry_count"], doc["engine_count"], doc["category_count"]))
