<#
Makes a dated zip of everything in GraphVis that cannot be regenerated.

What is left out is the point: build/, .cache/ and vcpkg_installed/ are several
gigabytes of compiler output and downloaded packages, all of it reproducible
from what IS in the zip by running build.bat. Including them would turn a
40 MB archive into a slow multi-gigabyte one that is no safer.

A backup written next to the thing it is backing up protects you from your own
edits, not from losing the disk. Copy the file somewhere else afterwards.
#>
param(
  # Where to write the zip. Defaults to a backups/ folder inside the project.
  [string]$Destination = '',
  # Leave out reference/ (the GraphVis 17 source kept for the port). Saves
  # about 14 MB per archive if you already have that safe elsewhere.
  [switch]$NoReference,
  # Leave out .git. Not recommended - see the note below - but here for the
  # case where the history is already safe on a remote.
  [switch]$NoHistory
)
$ErrorActionPreference = 'Stop'
$Root = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path

if (-not $Destination) { $Destination = Join-Path $Root 'backups' }
New-Item -ItemType Directory -Force -Path $Destination | Out-Null

$stamp   = Get-Date -Format 'yyyy-MM-dd_HHmm'
$version = if (Test-Path (Join-Path $Root 'VERSION')) {
             (Get-Content (Join-Path $Root 'VERSION') -Raw).Trim()
           } else { 'unknown' }
$zipPath = Join-Path $Destination "GraphVis-$version-source-$stamp.zip"

# Regenerated by the build, or junk left by earlier shell mishaps. None of it
# belongs in a backup.
# .git is NOT in this list, and that is deliberate.
#
# It used to be, which made this a source backup that threw away the source's
# history: every commit, every message explaining why a fix is the shape it is,
# and every intermediate state to bisect against. All of it irreplaceable, and
# all of it a few megabytes - about a thousandth of what excluding build/ saves.
# A restore from an archive without it starts with no way to ask what changed
# or when. Pass -NoHistory if the history is genuinely safe elsewhere.
#
# `.tooling` WAS MISSING, and it is the biggest thing in the tree. It holds the
# vcpkg CLONE - ports/, versions/, downloads/, buildtrees/, packages/,
# installed/ and vcpkg's own .git - plus the sccache compiler cache. That is
# hundreds of thousands of small files and several gigabytes, every byte of it
# re-fetched by the build. `vcpkg_installed` was excluded (the consumed output)
# and the thing that produces it was not, which is the same omission twice.
# A backup that took eighteen minutes to reach 37 MB and was still going is how
# it was noticed.
#
# `gallery` is 434 PNGs regenerated by the sweep, and PNG does not compress
# again, so it is pure cost. `Claude outputs` is delivered files, including
# stale duplicates of source.
$excludeDirs = @('build', '.cache', 'vcpkg_installed', 'backups',
                 'node_modules', '__pycache__', '.venv', 'dist',
                 '.tooling', 'gallery', 'Claude outputs', 'target',
                 'graph-check')
if ($NoHistory) { $excludeDirs += '.git' }
$excludeExt  = @('.etl', '.obj', '.ilk', '.pdb', '.exe', '.dll', '.lib')

Write-Host "Collecting files from $Root" -ForegroundColor Cyan
$files = Get-ChildItem -Path $Root -Recurse -File -Force | Where-Object {
  $relative = $_.FullName.Substring($Root.Length).TrimStart('\')
  $firstSegment = ($relative -split '\\')[0]
  $parts = $relative -split '\\'

  if ($excludeDirs -contains $firstSegment) { return $false }
  foreach ($p in $parts) { if ($excludeDirs -contains $p) { return $false } }
  if ($excludeExt -contains $_.Extension.ToLower()) { return $false }
  if ($NoReference -and $firstSegment -eq 'reference') { return $false }
  return $true
}

$totalMb = [math]::Round(($files | Measure-Object -Property Length -Sum).Sum / 1MB, 1)
Write-Host ("  {0} files, {1} MB before compression" -f $files.Count, $totalMb)

# Said before the slow part rather than discovered during it. A source tree
# this size is a few thousand files; tens of thousands means an exclusion has
# been missed again, and it is worth knowing that in the second it takes to
# read rather than in the twenty minutes it takes to compress.
if ($files.Count -gt 20000 -or $totalMb -gt 400) {
  Write-Host ""
  Write-Host ("  That is a lot. {0} files / {1} MB suggests a build or toolchain" -f $files.Count, $totalMb) -ForegroundColor Yellow
  Write-Host "  folder is being swept in. Ctrl+C now and check `$excludeDirs." -ForegroundColor Yellow
  Write-Host ""
  Start-Sleep -Seconds 5
}

# Said out loud, because "did my history get backed up" should not need the
# archive to be opened to answer.
$historyFiles = @($files | Where-Object { ($_.FullName.Substring($Root.Length).TrimStart('\') -split '\\')[0] -eq '.git' })
if ($historyFiles.Count -gt 0) {
  $historyMb = [math]::Round(($historyFiles | Measure-Object -Property Length -Sum).Sum / 1MB, 1)
  Write-Host ("  including the git history: {0} files, {1} MB" -f $historyFiles.Count, $historyMb) -ForegroundColor DarkGray
} else {
  Write-Host "  WITHOUT the git history (-NoHistory). Make sure it is safe somewhere else." -ForegroundColor Yellow
}

# Staged into a temporary tree so the archive keeps its folder structure and the
# exclusions actually apply - Compress-Archive has no exclude of its own.
$staging = Join-Path ([System.IO.Path]::GetTempPath()) "graphvis-backup-$stamp"
if (Test-Path $staging) { Remove-Item $staging -Recurse -Force }
New-Item -ItemType Directory -Force -Path $staging | Out-Null

foreach ($f in $files) {
  $relative = $f.FullName.Substring($Root.Length).TrimStart('\')
  $target   = Join-Path $staging $relative
  New-Item -ItemType Directory -Force -Path (Split-Path $target -Parent) | Out-Null
  Copy-Item $f.FullName $target -Force
}

Write-Host "Compressing to $zipPath" -ForegroundColor Cyan
if (Test-Path $zipPath) { Remove-Item $zipPath -Force }
Compress-Archive -Path (Join-Path $staging '*') -DestinationPath $zipPath -CompressionLevel Optimal
Remove-Item $staging -Recurse -Force

$zipMb = [math]::Round((Get-Item $zipPath).Length / 1MB, 1)
Write-Host ""
Write-Host "Backup written: $zipPath" -ForegroundColor Green
Write-Host ("  {0} MB  ({1} files)" -f $zipMb, $files.Count)
Write-Host ""
Write-Host "This zip is on the same disk as the project it came from." -ForegroundColor Yellow
Write-Host "Copy it to OneDrive, a USB drive or another machine to be a real backup." -ForegroundColor Yellow

# Old archives are the reason a backup folder quietly fills a disk. Keep ten.
$old = Get-ChildItem $Destination -Filter 'GraphVis-*-source-*.zip' |
       Sort-Object LastWriteTime -Descending | Select-Object -Skip 10
if ($old) {
  Write-Host ""
  Write-Host ("Removing {0} archive(s) older than the last ten." -f $old.Count) -ForegroundColor DarkGray
  $old | Remove-Item -Force
}
