<#
Makes a dated zip of everything in GraphVis that cannot be regenerated.

What is left out is the point: build/, .cache/ and vcpkg_installed/ are several
gigabytes of compiler output and downloaded packages, all of it reproducible
from what IS in the zip by running build.bat. Including them would turn a
40 MB archive into a slow multi-gigabyte one that is no safer.

A backup written next to the thing it is backing up protects you from your own
edits, not from losing the disk. Copy the file somewhere else afterwards.
#>
param(
  # Where to write the zip. Defaults to a backups/ folder inside the project.
  [string]$Destination = '',
  # Leave out reference/ (the GraphVis 17 source kept for the port). Saves
  # about 14 MB per archive if you already have that safe elsewhere.
  [switch]$NoReference
)
$ErrorActionPreference = 'Stop'
$Root = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path

if (-not $Destination) { $Destination = Join-Path $Root 'backups' }
New-Item -ItemType Directory -Force -Path $Destination | Out-Null

$stamp   = Get-Date -Format 'yyyy-MM-dd_HHmm'
$version = if (Test-Path (Join-Path $Root 'VERSION')) {
             (Get-Content (Join-Path $Root 'VERSION') -Raw).Trim()
           } else { 'unknown' }
$zipPath = Join-Path $Destination "GraphVis-$version-source-$stamp.zip"

# Regenerated by the build, or junk left by earlier shell mishaps. None of it
# belongs in a backup.
$excludeDirs = @('build', '.cache', 'vcpkg_installed', 'backups', '.git',
                 'node_modules', '__pycache__', '.venv', 'dist')
$excludeExt  = @('.etl', '.obj', '.ilk', '.pdb', '.exe', '.dll', '.lib')

Write-Host "Collecting files from $Root" -ForegroundColor Cyan
$files = Get-ChildItem -Path $Root -Recurse -File -Force | Where-Object {
  $relative = $_.FullName.Substring($Root.Length).TrimStart('\')
  $firstSegment = ($relative -split '\\')[0]
  $parts = $relative -split '\\'

  if ($excludeDirs -contains $firstSegment) { return $false }
  foreach ($p in $parts) { if ($excludeDirs -contains $p) { return $false } }
  if ($excludeExt -contains $_.Extension.ToLower()) { return $false }
  if ($NoReference -and $firstSegment -eq 'reference') { return $false }
  return $true
}

$totalMb = [math]::Round(($files | Measure-Object -Property Length -Sum).Sum / 1MB, 1)
Write-Host ("  {0} files, {1} MB before compression" -f $files.Count, $totalMb)

# Staged into a temporary tree so the archive keeps its folder structure and the
# exclusions actually apply - Compress-Archive has no exclude of its own.
$staging = Join-Path ([System.IO.Path]::GetTempPath()) "graphvis-backup-$stamp"
if (Test-Path $staging) { Remove-Item $staging -Recurse -Force }
New-Item -ItemType Directory -Force -Path $staging | Out-Null

foreach ($f in $files) {
  $relative = $f.FullName.Substring($Root.Length).TrimStart('\')
  $target   = Join-Path $staging $relative
  New-Item -ItemType Directory -Force -Path (Split-Path $target -Parent) | Out-Null
  Copy-Item $f.FullName $target -Force
}

Write-Host "Compressing to $zipPath" -ForegroundColor Cyan
if (Test-Path $zipPath) { Remove-Item $zipPath -Force }
Compress-Archive -Path (Join-Path $staging '*') -DestinationPath $zipPath -CompressionLevel Optimal
Remove-Item $staging -Recurse -Force

$zipMb = [math]::Round((Get-Item $zipPath).Length / 1MB, 1)
Write-Host ""
Write-Host "Backup written: $zipPath" -ForegroundColor Green
Write-Host ("  {0} MB  ({1} files)" -f $zipMb, $files.Count)
Write-Host ""
Write-Host "This zip is on the same disk as the project it came from." -ForegroundColor Yellow
Write-Host "Copy it to OneDrive, a USB drive or another machine to be a real backup." -ForegroundColor Yellow

# Old archives are the reason a backup folder quietly fills a disk. Keep ten.
$old = Get-ChildItem $Destination -Filter 'GraphVis-*-source-*.zip' |
       Sort-Object LastWriteTime -Descending | Select-Object -Skip 10
if ($old) {
  Write-Host ""
  Write-Host ("Removing {0} archive(s) older than the last ten." -f $old.Count) -ForegroundColor DarkGray
  $old | Remove-Item -Force
}
