$ErrorActionPreference = 'Continue'
$Root = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
Write-Host ("RUN-STAMP {0}" -f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss'))

# A GraphVis left running by a previous run - typically sitting on its
# "could not start" dialog - keeps a lock on graphvis.exe and makes the next
# link fail for reasons that look nothing like the real cause. Clear it first.
$stale = Get-Process graphvis -ErrorAction SilentlyContinue
if ($stale) {
  Write-Host ("Stopping {0} stale graphvis process(es) holding the exe" -f $stale.Count)
  $stale | Stop-Process -Force -ErrorAction SilentlyContinue
  Start-Sleep -Seconds 2
}

Write-Host "########## CLEAN STAGE ##########"
$stage = Join-Path $Root 'build/stage-fast'
if (Test-Path $stage) {
  # stage-fast is entirely generated by 'cmake --install'. Wipe the QML module
  # so a stale copy cannot shadow the one inside the exe.
  Remove-Item (Join-Path $stage 'qml') -Recurse -Force -ErrorAction SilentlyContinue
  Write-Host "removed stage-fast\qml"

  # Nothing else is ever cleaned here, so anything cmake --install stops
  # producing lingers in the staged app forever. Two things had been sitting in
  # it: a 79 MB Arrow Flight worker from back when that option defaulted on,
  # and - from a stray configure that used the staging folder as a BUILD
  # directory - a complete build tree including a 964 MB vcpkg_installed. None
  # of these are install output; cmake --install never writes a .rcc or a
  # vcpkg_installed into a prefix.
  $debris = @('vcpkg_installed','CMakeFiles','.qt','.rcc','app','native',
              'graphvis-worker.exe','graphvis-worker')
  foreach ($name in $debris) {
    $path = Join-Path $stage $name
    if (Test-Path $path) {
      $mb = 0
      try {
        $mb = [math]::Round((Get-ChildItem $path -Recurse -File -ErrorAction SilentlyContinue |
                             Measure-Object Length -Sum).Sum / 1MB, 1)
      } catch {}
      Remove-Item $path -Recurse -Force -ErrorAction SilentlyContinue
      if (-not (Test-Path $path)) { Write-Host ("removed stage-fast\{0} ({1} MB - not install output)" -f $name, $mb) }
    }
  }
}

# Two shipped scripts could not run at all, and the daily build never touched
# either of them, so nothing said so. Parse-checking every script takes under a
# second and this is the run that reads the result.
Write-Host "`n########## SCRIPT PARSE CHECK ##########"
try { & (Join-Path $PSScriptRoot 'Check-Scripts.ps1') -Quiet } catch {
  Write-Host "[SCRIPT CHECK ERROR] $($_.Exception.Message)"
}

Write-Host "`n########## BUILD ##########"
$script:BuildOk = $true
try { & (Join-Path $PSScriptRoot 'Quick-Build.ps1') } catch {
  $script:BuildOk = $false
  Write-Host "[BUILD ERROR] $($_.Exception.Message)"; Write-Host $_.ScriptStackTrace
}
if (-not $script:BuildOk) {
  # Never let a stale executable from a previous build be reported as a pass.
  Write-Host "`n>>> BUILD FAILED - any run result below is the PREVIOUS binary <<<"
}

Write-Host "`n########## GENERATED qmldir ##########"
$qd = Join-Path $Root 'build/windows-fast/app/GraphVis/qmldir'
if (Test-Path $qd) { Get-Content $qd -TotalCount 4 | Write-Host } else { Write-Host "(not generated)" }

$logDir = Join-Path $env:LOCALAPPDATA 'GraphVis\GraphVis 18.4\18.4\logs'
$srcLog = Join-Path $logDir 'startup.log'

function Try-Run($label, $dir, [int]$seconds, [switch]$LeaveOpen) {
  Write-Host "`n########## RUN: $label ##########"
  $exe = Join-Path $dir 'graphvis.exe'
  if (-not (Test-Path $exe)) { Write-Host "[SKIP] $exe not present"; return }
  Write-Host ("exe built: {0}" -f (Get-Item $exe).LastWriteTime)
  Remove-Item $srcLog -Force -ErrorAction SilentlyContinue
  $env:QT_FORCE_STDERR_LOGGING = '1'
  Remove-Item Env:\QT_DEBUG_PLUGINS -ErrorAction SilentlyContinue
  $env:QT_LOGGING_RULES = 'qt.qml.import.warning=true'
  $p = Start-Process -FilePath $exe -WorkingDirectory $dir -PassThru -ErrorAction SilentlyContinue
  if (-not $p) { Write-Host "[FAIL] loader refused to start it"; return }
  $exited = $p.WaitForExit($seconds * 1000)
  if ($exited) { Write-Host ("[EXIT] code 0x{0:X8}" -f $p.ExitCode) }
  else {
    Write-Host "[ALIVE] still running after ${seconds}s"
    if (-not $LeaveOpen) { $p.Kill(); Start-Sleep 2 }
  }
  Write-Host "--- startup.log ---"
  if (Test-Path $srcLog) {
    Copy-Item $srcLog (Join-Path $Root "startup-$label.txt") -Force
    Get-Content $srcLog | Write-Host
    if (Select-String -Path $srcLog -Pattern 'window created successfully' -Quiet) {
      Write-Host "`n>>> RESULT: $label OPENED ITS WINDOW <<<"
    } else {
      Write-Host "`n>>> RESULT: $label did NOT reach the main window <<<"
    }
  } else { Write-Host "[no startup.log]" }
}

# build/windows-fast is an intermediate build tree, not a deployed layout:
# Qt's own QML modules and graphvis_ffi.dll are not beside the exe there, so it
# always fails with 'module "QtQuick.Controls" is not installed'. That is
# expected and is not a defect. Only the staged layout is a runnable app.
Write-Host "`n########## VECTOR EXPORT SELF-TEST ##########"
$exe = Join-Path $Root 'build/stage-fast/graphvis.exe'
if (Test-Path $exe) {
  $pdf = Join-Path $Root 'build/selftest-plot.pdf'
  Remove-Item $pdf -Force -ErrorAction SilentlyContinue
  & $exe --selftest-plot $pdf 2>&1 | Write-Host
  Write-Host "selftest exit code: $LASTEXITCODE"
  if (Test-Path $pdf) { Write-Host ("selftest file: {0} bytes" -f (Get-Item $pdf).Length) }
} else { Write-Host "[SKIP] graphvis.exe not present" }

Try-Run 'stage'     (Join-Path $Root 'build/stage-fast')  45 -LeaveOpen
if (-not $script:BuildOk) { Write-Host "`n>>> REMINDER: THE BUILD FAILED. Results above are stale. <<<" }
Write-Host "`n########## END ##########"
