<#
Generate THIRD-PARTY-NOTICES.md from the libraries the release actually ships.

Why generated rather than written by hand: a notice file kept by hand is a
notice file that goes stale the first time a dependency is added, and the one
thing a legal notice must be is current. This reads the two things vcpkg already
knows - which port owns which installed file, and what each port's copyright
says - and reports only the ports whose binaries are in the staged release.

That last restriction matters. `vcpkg.json` names five dependencies; the build
tree contains about 140 ports, most of them Boost headers and build-time tools
that are never redistributed. The obligation attaches to what is handed to a
user, so the staged folder is the authority, not the manifest.

  -Stage    the staged release folder      (default build/stage)
  -Vcpkg    the vcpkg_installed folder     (default build/windows-release/vcpkg_installed)
  -Out      the file to write              (default THIRD-PARTY-NOTICES.md)
  -Triplet  vcpkg triplet                  (default x64-windows)

Run it after a release build and commit the result:

    powershell -NoProfile -ExecutionPolicy Bypass -File tools\Generate-Notices.ps1
#>
param(
  [string]$Stage   = "",
  [string]$Vcpkg   = "",
  [string]$Out     = "",
  [string]$Triplet = "x64-windows"
)
$ErrorActionPreference = 'Stop'
$Root = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
if (-not $Stage) { $Stage = Join-Path $Root 'build/stage' }
if (-not $Vcpkg) { $Vcpkg = Join-Path $Root "build/windows-release/vcpkg_installed" }
if (-not $Out)   { $Out   = Join-Path $Root 'THIRD-PARTY-NOTICES.md' }

if (-not (Test-Path $Stage)) { throw "No staged release at $Stage. Build one first (tools\Quick-Build.ps1 -Full)." }
$info = Join-Path $Vcpkg 'vcpkg/info'
if (-not (Test-Path $info)) { throw "No vcpkg install database at $info." }

# What the release actually contains, by file name. Only the leaf name is
# needed: a port's .list records paths relative to the triplet folder, and the
# deploy step flattens the DLLs into the stage root.
$shipped = [System.Collections.Generic.HashSet[string]]::new(
  [string[]](Get-ChildItem -Path $Stage -Recurse -File | ForEach-Object { $_.Name.ToLowerInvariant() }),
  [System.StringComparer]::OrdinalIgnoreCase)
Write-Host "Staged release contains $($shipped.Count) files" -ForegroundColor Cyan

$ports = @()
foreach ($list in Get-ChildItem -Path $info -Filter '*.list') {
  # <port>_<version>_<triplet>.list, and a version may itself contain
  # underscores, so split from the right.
  $stem  = [IO.Path]::GetFileNameWithoutExtension($list.Name)
  $parts = $stem -split '_'
  if ($parts.Count -lt 3) { continue }
  $port    = $parts[0]
  $version = ($parts[1..($parts.Count - 2)] -join '_')

  $owns = $false
  foreach ($line in [IO.File]::ReadLines($list.FullName)) {
    if ($line -notmatch '\.(dll|exe)$') { continue }
    if ($shipped.Contains([IO.Path]::GetFileName($line))) { $owns = $true; break }
  }
  if (-not $owns) { continue }

  $copyright = Join-Path $Vcpkg "$Triplet/share/$port/copyright"
  $ports += [pscustomobject]@{
    Port      = $port
    Version   = $version
    Copyright = if (Test-Path $copyright) { (Get-Content $copyright -Raw) } else { "" }
    HasText   = (Test-Path $copyright)
  }
}
$ports = $ports | Sort-Object Port -Unique
Write-Host "$($ports.Count) ports ship a binary in this release" -ForegroundColor Cyan
$missing = @($ports | Where-Object { -not $_.HasText })
if ($missing.Count) {
  # Not fatal, but it must be visible: a shipped library with no copyright text
  # is exactly the gap this file exists to close.
  Write-Host ("No copyright text found for: " + ($missing.Port -join ', ')) -ForegroundColor Yellow
}

$version = (Get-Content (Join-Path $Root 'VERSION') -Raw).Trim()
$sb = [System.Text.StringBuilder]::new()
$null = $sb.AppendLine("# Third-party notices")
$null = $sb.AppendLine()
$null = $sb.AppendLine("GraphVis $version is distributed with the libraries below. Each remains under")
$null = $sb.AppendLine("its own licence and its own copyright; this file reproduces those notices as")
$null = $sb.AppendLine("those licences require.")
$null = $sb.AppendLine()
$null = $sb.AppendLine("Generated by ``tools/Generate-Notices.ps1`` from the ports whose binaries are")
$null = $sb.AppendLine("present in the staged release. Do not edit it by hand - regenerate it after")
$null = $sb.AppendLine("any dependency change.")
$null = $sb.AppendLine()
$null = $sb.AppendLine("## Qt")
$null = $sb.AppendLine()
$null = $sb.AppendLine("Qt is used under the **GNU Lesser General Public License version 3**. Two")
$null = $sb.AppendLine("consequences, both of which this release honours:")
$null = $sb.AppendLine()
$null = $sb.AppendLine("- Qt is linked **dynamically** and shipped as separate ``Qt6*.dll`` files, so a")
$null = $sb.AppendLine("  user may replace them with their own build of the same Qt version.")
$null = $sb.AppendLine("- The Qt source for the version used is available from https://download.qt.io/ ,")
$null = $sb.AppendLine("  and the exact version is recorded in the table below.")
$null = $sb.AppendLine()
$null = $sb.AppendLine("## Components")
$null = $sb.AppendLine()
$null = $sb.AppendLine("| Component | Version |")
$null = $sb.AppendLine("|---|---|")
foreach ($p in $ports) { $null = $sb.AppendLine("| $($p.Port) | $($p.Version) |") }
$null = $sb.AppendLine()
$null = $sb.AppendLine("The Rust crates compiled into ``graphvis_ffi.dll`` are listed in")
$null = $sb.AppendLine("``native/Cargo.lock``; run ``cargo license`` or ``cargo about`` in ``native/`` for")
$null = $sb.AppendLine("their notices. The optional Python science components are installed from PyPI")
$null = $sb.AppendLine("into the user's own environment rather than redistributed here, and each keeps")
$null = $sb.AppendLine("its own licence.")
$null = $sb.AppendLine()
$null = $sb.AppendLine("## Full licence texts")
foreach ($p in $ports) {
  $null = $sb.AppendLine()
  $null = $sb.AppendLine("### $($p.Port) $($p.Version)")
  $null = $sb.AppendLine()
  if ($p.HasText) {
    $null = $sb.AppendLine('```')
    $null = $sb.AppendLine($p.Copyright.TrimEnd())
    $null = $sb.AppendLine('```')
  } else {
    $null = $sb.AppendLine("*No copyright file was installed for this port. Check upstream before release.*")
  }
}

Set-Content -Path $Out -Value $sb.ToString() -Encoding UTF8
Write-Host "Wrote $Out" -ForegroundColor Green
