#!/usr/bin/env python3
"""Write config/citation_styles.json from the Python style table.

ONE SOURCE, GENERATED INTO TWO PLACES. The picker in the interface and the
formatter in the science service have to offer the same set of styles, in the
same order, under the same names - and they are written in different languages
and shipped in different ways. A hand-kept list in the QML was the arrangement
that produced the fault this whole area is being fixed for: a `style` argument
that was accepted and silently ignored, so a user who chose IEEE got APA with
nothing to tell them their choice had done nothing.

So the table in `graphvis_science/citation_styles.py` is the source, this writes
the interface's copy of it, and `tools/audit/checks_project.py` fails the audit
when the two disagree. Adding a style is a row in that table and a run of this;
there is no second place to remember.

Run:  python3 tools/make_citation_styles.py [--check]
"""
from __future__ import annotations

import argparse
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "services" / "python"))

from graphvis_science.citation_styles import PINNED, ordered   # noqa: E402

OUT = ROOT / "config" / "citation_styles.json"


def payload() -> dict:
    styles = []
    for style in ordered():
        row = {
            "key": style.key,
            "label": style.label,
            "family": style.family,
            # Shown as a small note under the picker, so a person choosing a
            # style can see whether its rules were taken from the publisher or
            # from a library guide. Omitted when there is nothing to say.
            "source": style.source,
            "captionAbove": bool(style.caption_above),
        }
        if style.caveat:
            row["caveat"] = style.caveat
        styles.append(row)
    return {
        "note": ("Generated by tools/make_citation_styles.py from "
                 "graphvis_science/citation_styles.py. Do not edit by hand: "
                 "the audit compares the two and fails when they differ."),
        "pinned": list(PINNED),
        "styles": styles,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="exit non-zero if the file on disk is out of date")
    args = parser.parse_args()

    text = json.dumps(payload(), indent=1, ensure_ascii=False) + "\n"
    if args.check:
        if not OUT.exists():
            print(f"{OUT} does not exist; run this without --check")
            return 1
        if OUT.read_text(encoding="utf-8") != text:
            print(f"{OUT} is out of date with the style table")
            return 1
        print(f"{OUT} is up to date ({len(payload()['styles'])} styles)")
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT} ({len(payload()['styles'])} styles)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
