# =========================================================================
# export_code.py - reproducibility script generation for active GraphVis plots.
# =========================================================================
from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pandas as pd


def _filtered_frame(spec, ds):
    """Apply the active non-destructive GraphVis filters before code export."""
    df = ds.df.copy()
    for role, bounds in (getattr(spec, "clipping_ranges", {}) or {}).items():
        col = (getattr(spec, "mappings", {}) or {}).get(role)
        if col in df.columns and bounds and len(bounds) == 2:
            lo, hi = sorted(map(float, bounds))
            vals = pd.to_numeric(df[col], errors="coerce")
            df = df.loc[vals.between(lo, hi, inclusive="both")]
    mapped = []
    for role in ("x", "y", "z", "w", "v"):
        col = (getattr(spec, "mappings", {}) or {}).get(role)
        if col in df.columns and col not in mapped:
            mapped.append(col)
    if getattr(spec, "noise_filter_enabled", False) and mapped and not df.empty:
        threshold = float(getattr(spec, "noise_filter_threshold", 2.5))
        keep = np.ones(len(df), dtype=bool)
        for c in mapped:
            v = pd.to_numeric(df[c], errors="coerce").to_numpy(float)
            finite = np.isfinite(v)
            if getattr(spec, "noise_filter_method", "Z-Score") == "IQR":
                q1, q3 = np.nanpercentile(v[finite], [25, 75]) if finite.any() else (0, 0)
                iqr = q3 - q1
                if iqr > 0:
                    keep &= finite & (v >= q1 - threshold * iqr) & (v <= q3 + threshold * iqr)
            else:
                mu, sd = np.nanmean(v), np.nanstd(v)
                if np.isfinite(sd) and sd > 0:
                    keep &= finite & (np.abs((v - mu) / sd) <= threshold)
        df = df.loc[keep].copy()
    if getattr(spec, "outlier_mask", False) and mapped and not df.empty:
        method = getattr(spec, "mask_method", "Percentile Capping")
        if method == "k-NN Distance Filter":
            k = max(1, min(int(getattr(spec, "mask_min_neighbors", 8) or 8), 64))
            pts = df[mapped].apply(pd.to_numeric, errors="coerce").to_numpy(float)
            ok = np.all(np.isfinite(pts), axis=1)
            if ok.sum() > k + 1:
                try:
                    from scipy.spatial import cKDTree
                    scale = np.nanstd(pts[ok], axis=0)
                    scale[~np.isfinite(scale) | (scale == 0)] = 1.0
                    dk = cKDTree(pts[ok] / scale).query(pts[ok] / scale, k=k + 1)[0][:, -1]
                    med = float(np.median(dk)); mad = float(np.median(np.abs(dk - med))) or 1e-12
                    keep_idx = np.flatnonzero(ok)[dk <= med + 3.0 * 1.4826 * mad]
                    df = df.iloc[keep_idx]
                except Exception:
                    pass
        else:
            for c in mapped:
                v = pd.to_numeric(df[c], errors="coerce")
                if method == "Z-Score Clip":
                    mu, sd = v.mean(), v.std(ddof=0)
                    if pd.notna(sd) and sd > 0:
                        df[c] = v.clip(mu - 3 * sd, mu + 3 * sd)
                else:
                    lo, hi = v.quantile(0.01), v.quantile(0.99)
                    if pd.notna(lo) and pd.notna(hi) and hi > lo:
                        df[c] = v.clip(lo, hi)
    return df.reset_index(drop=True)



def export_python(spec, path: str) -> list[str]:
    """Write a standalone matplotlib reproduction script plus source CSVs."""
    path = str(path)
    out_path = Path(path).resolve()
    base = out_path.parent
    base.mkdir(parents=True, exist_ok=True)
    data_files = []
    for i, (name, ds) in enumerate(spec.datasets.items(), 1):
        fname = f"{out_path.stem}_data_{i}.csv"
        _filtered_frame(spec, ds).to_csv(base / fname, index=False)
        data_files.append((str(name), fname))

    spec_json = json.dumps(spec.to_dict(), default=str)
    code = f'''# Auto-generated by GraphVis.
# PlotSpec snapshot is embedded for reproducibility.
import json
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.ticker import LogFormatterMathtext, LogLocator, NullFormatter

SPEC = json.loads({spec_json!r})
DATASETS = {data_files!r}
frames = [(name, pd.read_csv(file)) for name, file in DATASETS]
chart = SPEC.get("chart_type", "Line Chart")
m = SPEC.get("mappings", {{}})
fig = plt.figure(figsize=tuple(SPEC.get("figsize", [9, 6.5])))

def col(df, key, fallback=0):
    c = m.get(key)
    if c in df.columns:
        return c
    nums = list(df.select_dtypes(include=[np.number]).columns)
    return nums[fallback] if len(nums) > fallback else None

if chart in ("3D Scatter", "3D Line", "3D Bar", "3D Horizontal Bar", "3D Stem", "Comet 3D"):
    ax = fig.add_subplot(111, projection="3d")
else:
    ax = fig.add_subplot(111)

for name, df in frames:
    x = col(df, "x", 0)
    y = col(df, "y", 1)
    z = col(df, "z", 2)
    if chart == "Histogram":
        if x:
            ax.hist(df[x].dropna().to_numpy(), bins=40, alpha=0.7, label=name)
    elif chart in ("Bar", "Horizontal Bar"):
        if x and y:
            sub = df[[x, y]].dropna()
            vals = sub[y].to_numpy()
            pos = np.arange(len(vals))
            (ax.barh(pos, vals, label=name) if chart == "Horizontal Bar" else ax.bar(pos, vals, label=name))
    elif chart == "3D Scatter":
        if x and y and z:
            sub = df[[x, y, z]].dropna()
            ax.scatter(sub[x], sub[y], sub[z], label=name)
    elif chart == "3D Line":
        if x and y and z:
            sub = df[[x, y, z]].dropna()
            ax.plot(sub[x], sub[y], sub[z], label=name)
    elif chart in ("4D / 5D Scatter", "Swarm"):
        if x and y:
            sub = df[[x, y]].dropna()
            ax.scatter(sub[x], sub[y], label=name, alpha=0.8)
    elif chart == "Stairs":
        if x and y:
            sub = df[[x, y]].dropna().sort_values(x)
            ax.step(sub[x], sub[y], where="mid", label=name)
    elif chart == "Area":
        if x and y:
            sub = df[[x, y]].dropna().sort_values(x)
            ax.fill_between(sub[x], sub[y], alpha=0.4, label=name)
    else:
        if x and y:
            sub = df[[x, y]].dropna().sort_values(x)
            ax.plot(sub[x], sub[y], label=name, color=SPEC.get("series_color", "#2980B9"),
                    linewidth=float(SPEC.get("line_width", 1.8)), marker=(SPEC.get("marker") or None))

style = SPEC.get("styling", {{}})
def st(key, default=""):
    return style.get(key, {{}}).get("text") or default

ax.set_title(st("Main Title", chart))
if frames:
    df0 = frames[0][1]
    x0 = col(df0, "x", 0)
    y0 = col(df0, "y", 1)
    if x0:
        ax.set_xlabel(st("X-Axis Label", x0))
    if y0:
        ax.set_ylabel(st("Y-Axis Label", y0))
def set_axis_scale(role, mode):
    setter = getattr(ax, f"set_{{role}}scale", None)
    axis = getattr(ax, f"{{role}}axis", None)
    if setter is None:
        return
    if str(mode).lower() == "log10":
        setter("log", base=10)
        axis.set_major_locator(LogLocator(base=10.0))
        axis.set_major_formatter(LogFormatterMathtext(base=10.0))
        axis.set_minor_locator(LogLocator(base=10.0, subs=np.arange(2, 10) * 0.1))
        axis.set_minor_formatter(NullFormatter())
    else:
        setter("linear")

set_axis_scale("x", SPEC.get("x_scale", "Linear"))
set_axis_scale("y", SPEC.get("y_scale", "Linear"))
if hasattr(ax, "set_zscale"):
    set_axis_scale("z", SPEC.get("z_scale", "Linear"))
ax.grid(bool(SPEC.get("grid_visible", True)))
if SPEC.get("show_legend", True):
    ax.legend()
fig.tight_layout()
plt.show()
'''
    out_path.write_text(code, encoding="utf-8")
    return [str(out_path)] + [str(base / f) for _, f in data_files]


def export_matlab(spec, path: str) -> list[str]:
    """Write a MATLAB reproduction script plus source CSVs."""
    path = str(path)
    out_path = Path(path).resolve()
    base = out_path.parent
    base.mkdir(parents=True, exist_ok=True)
    files = []
    for i, (name, ds) in enumerate(spec.datasets.items(), 1):
        fname = f"{out_path.stem}_data_{i}.csv"
        _filtered_frame(spec, ds).to_csv(base / fname, index=False)
        files.append((str(name), fname, ds))

    lines = ["% Auto-generated by GraphVis", "close all; figure; hold on; grid on;"]
    for i, (name, fname, ds) in enumerate(files, 1):
        lines.append(f"T{i} = readtable('{fname}');")
        nums = ds.numeric_columns
        x = spec.mappings.get("x") if spec.mappings.get("x") in ds.df.columns else (nums[0] if nums else None)
        y = spec.mappings.get("y") if spec.mappings.get("y") in ds.df.columns else (nums[1] if len(nums) > 1 else None)
        z = spec.mappings.get("z") if spec.mappings.get("z") in ds.df.columns else (nums[2] if len(nums) > 2 else None)
        def arr(col):
            esc = str(col).replace("'", "''")
            return f"T{i}{{:, '{esc}'}}"
        c = spec.chart_type
        safe_name = name.replace("'", "''")
        if c == "3D Scatter" and x and y and z:
            lines.append(f"scatter3({arr(x)}, {arr(y)}, {arr(z)}, 24, 'filled', 'DisplayName', '{safe_name}');")
        elif c == "3D Line" and x and y and z:
            lines.append(f"plot3({arr(x)}, {arr(y)}, {arr(z)}, 'DisplayName', '{safe_name}');")
        elif c == "Histogram" and x:
            lines.append(f"histogram({arr(x)}, 'DisplayName', '{safe_name}');")
        elif c == "Stairs" and x and y:
            lines.append(f"stairs({arr(x)}, {arr(y)}, 'DisplayName', '{safe_name}');")
        elif c in ("4D / 5D Scatter", "Swarm") and x and y:
            lines.append(f"scatter({arr(x)}, {arr(y)}, 24, 'filled', 'DisplayName', '{safe_name}');")
        elif x and y:
            lines.append(f"plot({arr(x)}, {arr(y)}, 'LineWidth', 1.5, 'DisplayName', '{safe_name}');")

    title = (spec.styling.get("Main Title", {}).get("text") or spec.chart_type).replace("'", "''")
    lines.append(f"title('{title}');")
    if files:
        ds = files[0][2]
        nums = ds.numeric_columns
        x = spec.mappings.get("x") if spec.mappings.get("x") in ds.df.columns else (nums[0] if nums else "X")
        y = spec.mappings.get("y") if spec.mappings.get("y") in ds.df.columns else (nums[1] if len(nums) > 1 else "Y")
        xl = (spec.styling.get("X-Axis Label", {}).get("text") or str(x)).replace("'", "''")
        yl = (spec.styling.get("Y-Axis Label", {}).get("text") or str(y)).replace("'", "''")
        lines.extend([f"xlabel('{xl}');", f"ylabel('{yl}');"])
    if getattr(spec, "x_scale", "Linear") == "Log10":
        lines.append("set(gca,'XScale','log');")
    if getattr(spec, "y_scale", "Linear") == "Log10":
        lines.append("set(gca,'YScale','log');")
    if getattr(spec, "z_scale", "Linear") == "Log10" and any(c.startswith("3D") or c in ("Comet 3D",) for c in [spec.chart_type]):
        lines.append("set(gca,'ZScale','log');")
    lines.extend(["legend('show','Location','best');", "hold off;"])
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return [str(out_path)] + [str(base / f) for _, f, _ in files]
